#
# Gnu tool chain
#
ifeq ($(BIN_GNU_CC),)
BIN_GNU_CC=/usr/local/gcc-3.4.1_ssp/bin/gcc
endif
ifeq ($(BIN_GNU_CXX),)
BIN_GNU_CXX=/usr/local/gcc-3.4.1_ssp/bin/g++
endif
ifeq ($(BIN_GNU_AS),)
BIN_GNU_AS=/usr/local/gcc-3.4.1_ssp/bin/gcc
endif
ifeq ($(BIN_GNU_CPP),)
BIN_GNU_CPP=/usr/local/gcc-3.4.1_ssp/bin/gcc -E
endif
ifeq ($(BIN_GNU_LD),)
BIN_GNU_LD=/usr/local/gcc-3.4.1_ssp/bin/gcc
endif
ifeq ($(BIN_GNU_AR),)
BIN_GNU_AR=/usr/bin/ar
endif
ifeq ($(BIN_GNU_STRIP),)
BIN_GNU_STRIP=/usr/bin/strip
endif


ifeq ($(FLAGS_GNU_CC),)
FLAGS_GNU_CC=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_GNU_CC_DEP),)
FLAGS_GNU_CC_DEP=-MM -w
endif
ifeq ($(FLAGS_GNU_CC_DBG),)
FLAGS_GNU_CC_DBG=-g3
endif
ifeq ($(FLAGS_GNU_CC_OPT),)
FLAGS_GNU_CC_OPT=-O3
endif
ifeq ($(FLAGS_GNU_CC_PROFILE),)
FLAGS_GNU_CC_PROFILE=-pg
endif
ifeq ($(FLAGS_GNU_CC_COV),)
FLAGS_GNU_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_GNU_CC_NOASSERT),)
FLAGS_GNU_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_GNU_CC_REENT),)
FLAGS_GNU_CC_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_GNU_CXX),)
FLAGS_GNU_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Wmissing-prototypes \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_GNU_CXX_DEP),)
FLAGS_GNU_CXX_DEP=-MM -w
endif
ifeq ($(FLAGS_GNU_CXX_DBG),)
FLAGS_GNU_CXX_DBG=-g3
endif
ifeq ($(FLAGS_GNU_CXX_OPT),)
FLAGS_GNU_CXX_OPT=-O3
endif
ifeq ($(FLAGS_GNU_CXX_PROFILE),)
FLAGS_GNU_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_GNU_CXX_COV),)
FLAGS_GNU_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_GNU_CXX_NOASSERT),)
FLAGS_GNU_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_GNU_CXX_REENT),)
FLAGS_GNU_CXX_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_GNU_AS),)
FLAGS_GNU_AS=
endif
ifeq ($(FLAGS_GNU_AS_DEP),)
FLAGS_GNU_AS_DEP=-MM -w
endif
ifeq ($(FLAGS_GNU_AS_DBG),)
FLAGS_GNU_AS_DBG=-g3 -Wa,--gstabs
endif
ifeq ($(FLAGS_GNU_AS_OPT),)
FLAGS_GNU_AS_OPT=-O3
endif
ifeq ($(FLAGS_GNU_AS_PROFILE),)
FLAGS_GNU_AS_PROFILE=
endif
ifeq ($(FLAGS_GNU_AS_COV),)
FLAGS_GNU_AS_COV=
endif


ifeq ($(FLAGS_GNU_LD_EXE),)
FLAGS_GNU_LD_EXE=
endif
ifeq ($(FLAGS_GNU_LD_EXE_OPT),)
FLAGS_GNU_LD_EXE_OPT=
endif
ifeq ($(FLAGS_GNU_LD_EXE_DBG),)
FLAGS_GNU_LD_EXE_DBG=
endif
ifeq ($(FLAGS_GNU_LD_EXE_PROFILE),)
FLAGS_GNU_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_GNU_LD_EXE_COV),)
FLAGS_GNU_LD_EXE_COV=
endif

ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS),)
FLAGS_GNU_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS_OPT),)
FLAGS_GNU_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS_DBG),)
FLAGS_GNU_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_GNU_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS_COV),)
FLAGS_GNU_LD_EXE_LOADLIBS_LOADLIBS_COV=
endif

ifeq ($(FLAGS_GNU_LD_SHLIB),)
FLAGS_GNU_LD_SHLIB=-shared
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_OPT),)
FLAGS_GNU_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_DBG),)
FLAGS_GNU_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_PROFILE),)
FLAGS_GNU_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_COV),)
FLAGS_GNU_LD_SHLIB_COV=
endif

ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS),)
FLAGS_GNU_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_GNU_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_GNU_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_GNU_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS_COV),)
FLAGS_GNU_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_GNU_LD_INCOBJ),)
FLAGS_GNU_LD_INCOBJ=-Wl,-r
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_OPT),)
FLAGS_GNU_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_DBG),)
FLAGS_GNU_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_PROFILE),)
FLAGS_GNU_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_COV),)
FLAGS_GNU_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_GNU_AR_LIB),)
FLAGS_GNU_AR_LIB=rc
endif
ifeq ($(FLAGS_GNU_AR_LIB_OPT),)
FLAGS_GNU_AR_LIB_OPT=
endif
ifeq ($(FLAGS_GNU_AR_LIB_DBG),)
FLAGS_GNU_AR_LIB_DBG=
endif
ifeq ($(FLAGS_GNU_AR_LIB_PROFILE),)
FLAGS_GNU_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_GNU_AR_LIB_COV),)
FLAGS_GNU_AR_LIB_COV=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS),)
FLAGS_GNU_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS_OPT),)
FLAGS_GNU_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS_DBG),)
FLAGS_GNU_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_GNU_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS_COV),)
FLAGS_GNU_AR_LIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_GNU_STRIP_EXE),)
FLAGS_GNU_STRIP_EXE= --strip-unneeded
endif
ifeq ($(FLAGS_GNU_STRIP_SHLIB),)
FLAGS_GNU_STRIP_SHLIB= --discard-all
endif
ifeq ($(FLAGS_GNU_STRIP_LIB),)
FLAGS_GNU_STRIP_LIB= --discard-all
endif





#
# Vendor tool chain
#
ifeq ($(BIN_VENDOR_CC),)
BIN_VENDOR_CC=/usr/bin/gcc
endif
ifeq ($(BIN_VENDOR_CXX),)
BIN_VENDOR_CXX=/usr/bin/g++
endif
ifeq ($(BIN_VENDOR_AS),)
BIN_VENDOR_AS=/usr/bin/gcc
endif
ifeq ($(BIN_VENDOR_CPP),)
BIN_VENDOR_CPP=/usr/bin/gcc -E
endif
ifeq ($(BIN_VENDOR_LD),)
BIN_VENDOR_LD=/usr/bin/ld
endif
ifeq ($(BIN_VENDOR_AR),)
BIN_VENDOR_AR=/usr/bin/ar
endif
ifeq ($(BIN_VENDOR_STRIP),)
BIN_VENDOR_STRIP=/usr/bin/strip
endif



ifeq ($(FLAGS_VENDOR_CC),)
FLAGS_VENDOR_CC=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_VENDOR_CC_DEP),)
FLAGS_VENDOR_CC_DEP=-MM -w
endif
ifeq ($(FLAGS_VENDOR_CC_DBG),)
FLAGS_VENDOR_CC_DBG=-g
endif
ifeq ($(FLAGS_VENDOR_CC_OPT),)
FLAGS_VENDOR_CC_OPT=-O
endif
ifeq ($(FLAGS_VENDOR_CC_PROFILE),)
FLAGS_VENDOR_CC_PROFILE=--pg
endif
ifeq ($(FLAGS_VENDOR_CC_COV),)
FLAGS_VENDOR_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_VENDOR_CC_NOASSERT),)
FLAGS_VENDOR_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_VENDOR_CC_REENT),)
FLAGS_VENDOR_CC_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_VENDOR_CXX),)
FLAGS_VENDOR_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_VENDOR_CXX_DEP),)
FLAGS_VENDOR_CXX_DEP=-MM -w
endif
ifeq ($(FLAGS_VENDOR_CXX_DBG),)
FLAGS_VENDOR_CXX_DBG=-g
endif
ifeq ($(FLAGS_VENDOR_CXX_OPT),)
FLAGS_VENDOR_CXX_OPT=-O
endif
ifeq ($(FLAGS_VENDOR_CXX_PROFILE),)
FLAGS_VENDOR_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_VENDOR_CXX_COV),)
FLAGS_VENDOR_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_VENDOR_CXX_NOASSERT),)
FLAGS_VENDOR_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_VENDOR_CXX_REENT),)
FLAGS_VENDOR_CXX_REENT=-D_REENTRANT
endif


ifeq ($(FLAGS_VENDOR_AS),)
FLAGS_VENDOR_AS=
endif
ifeq ($(FLAGS_VENDOR_AS_DEP),)
FLAGS_VENDOR_AS_DEP=-MM -w
endif
ifeq ($(FLAGS_VENDOR_AS_DBG),)
FLAGS_VENDOR_AS_DBG=-g3 -Wa,--gstabs
endif
ifeq ($(FLAGS_VENDOR_AS_OPT),)
FLAGS_VENDOR_AS_OPT=-O3
endif
ifeq ($(FLAGS_VENDOR_AS_PROFILE),)
FLAGS_VENDOR_AS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_AS_COV),)
FLAGS_VENDOR_AS_COV=
endif


ifeq ($(FLAGS_VENDOR_LD_EXE),)
FLAGS_VENDOR_LD_EXE=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_OPT),)
FLAGS_VENDOR_LD_EXE_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_DBG),)
FLAGS_VENDOR_LD_EXE_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_PROFILE),)
FLAGS_VENDOR_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_COV),)
FLAGS_VENDOR_LD_EXE_COV=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS),)
FLAGS_VENDOR_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS_OPT),)
FLAGS_VENDOR_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS_DBG),)
FLAGS_VENDOR_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_VENDOR_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS_COV),)
FLAGS_VENDOR_LD_EXE_LOADLIBS_COV=
endif


ifeq ($(FLAGS_VENDOR_LD_SHLIB),)
FLAGS_VENDOR_LD_SHLIB=-shared
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_OPT),)
FLAGS_VENDOR_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_DBG),)
FLAGS_VENDOR_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_PROFILE),)
FLAGS_VENDOR_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_COV),)
FLAGS_VENDOR_LD_SHLIB_COV=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS_COV),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_VENDOR_LD_INCOBJ),)
FLAGS_VENDOR_LD_INCOBJ=-r
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_OPT),)
FLAGS_VENDOR_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_DBG),)
FLAGS_VENDOR_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_PROFILE),)
FLAGS_VENDOR_LD_INCOBJ_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_COV),)
FLAGS_VENDOR_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_VENDOR_AR_LIB),)
FLAGS_VENDOR_AR_LIB=rc
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_OPT),)
FLAGS_VENDOR_AR_LIB_OPT=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_DBG),)
FLAGS_VENDOR_AR_LIB_DBG=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_PROFILE),)
FLAGS_VENDOR_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_COV),)
FLAGS_VENDOR_AR_LIB_COV=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS),)
FLAGS_VENDOR_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS_OPT),)
FLAGS_VENDOR_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS_DBG),)
FLAGS_VENDOR_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_VENDOR_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS_COV),)
FLAGS_VENDOR_AR_LIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_VENDOR_STRIP_EXE),)
FLAGS_VENDOR_STRIP_EXE= --strip-unneeded
endif
ifeq ($(FLAGS_VENDOR_STRIP_SHLIB),)
FLAGS_VENDOR_STRIP_SHLIB= --discard-all
endif
ifeq ($(FLAGS_VENDOR_STRIP_LIB),)
FLAGS_VENDOR_STRIP_LIB= --discard-all
endif

#
# Purify & Gnu tool chain
#

_bin_purify=/opt/rational/releases/purify.i386_linux2.2003a.06.12/purify \
	-verbose \
	-cache-dir=$(BS_ARCH_TARGET_DIR) \
	-exit-status=yes \
	-inuse-at-exit=yes \
	-leaks-at-exit=yes \
	-fds-inuse-at-exit=yes

ifeq ($(BIN_PURIFY_CC),)
#BIN_PURIFY_CC=$(_bin_purify) $(BIN_GNU_CC)
BIN_PURIFY_CC=$(BIN_GNU_CC)
endif
ifeq ($(BIN_PURIFY_CXX),)
#BIN_PURIFY_CXX=$(_bin_purify) $(BIN_GNU_CXX)
BIN_PURIFY_CXX=$(BIN_GNU_CXX)
endif
ifeq ($(BIN_PURIFY_AS),)
#BIN_PURIFY_AS=$(_bin_purify) $(BIN_GNU_AS)
BIN_PURIFY_AS=$(BIN_GNU_AS)
endif
ifeq ($(BIN_PURIFY_CPP),)
BIN_PURIFY_CPP=$(BIN_GNU_CPP)
endif
ifeq ($(BIN_PURIFY_LD),)
BIN_PURIFY_LD=$(_bin_purify) $(BIN_GNU_LD)
endif
ifeq ($(BIN_PURIFY_AR),)
BIN_PURIFY_AR=$(BIN_GNU_AR)
endif
# Don't strip purify builds
ifeq ($(BIN_PURIFY_STRIP),)
BIN_PURIFY_STRIP=$(BIN_TRUE)
endif



ifeq ($(FLAGS_PURIFY_CC),)
FLAGS_PURIFY_CC=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused
#	-v #
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_PURIFY_CC_DEP),)
FLAGS_PURIFY_CC_DEP=-MM -w
endif
ifeq ($(FLAGS_PURIFY_CC_DBG),)
FLAGS_PURIFY_CC_DBG=-g3
endif
ifeq ($(FLAGS_PURIFY_CC_OPT),)
FLAGS_PURIFY_CC_OPT=-O3
endif
ifeq ($(FLAGS_PURIFY_CC_PROFILE),)
FLAGS_PURIFY_CC_PROFILE=-pg
endif
ifeq ($(FLAGS_PURIFY_CC_COV),)
FLAGS_PURIFY_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_PURIFY_CC_NOASSERT),)
FLAGS_PURIFY_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_PURIFY_CC_REENT),)
FLAGS_PURIFY_CC_REENT=-D_REENTRANT
endif


ifeq ($(FLAGS_PURIFY_CXX),)
FLAGS_PURIFY_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_PURIFY_CXX_DEP),)
FLAGS_PURIFY_CXX_DEP=-MM -w
endif
ifeq ($(FLAGS_PURIFY_CXX_DBG),)
FLAGS_PURIFY_CXX_DBG=-g3
endif
ifeq ($(FLAGS_PURIFY_CXX_OPT),)
FLAGS_PURIFY_CXX_OPT=-O3
endif
ifeq ($(FLAGS_PURIFY_CXX_PROFILE),)
FLAGS_PURIFY_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_PURIFY_CXX_COV),)
FLAGS_PURIFY_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_PURIFY_CXX_NOASSERT),)
FLAGS_PURIFY_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_PURIFY_CXX_REENT),)
FLAGS_PURIFY_CXX_REENT=-D_REENTRANT
endif


ifeq ($(FLAGS_PURIFY_AS),)
FLAGS_PURIFY_AS=
endif
ifeq ($(FLAGS_PURIFY_AS_DEP),)
FLAGS_PURIFY_AS_DEP=-MM -w
endif
ifeq ($(FLAGS_PURIFY_AS_DBG),)
FLAGS_PURIFY_AS_DBG=-g3
endif
ifeq ($(FLAGS_PURIFY_AS_OPT),)
FLAGS_PURIFY_AS_OPT=-O3
endif
ifeq ($(FLAGS_PURIFY_AS_PROFILE),)
FLAGS_PURIFY_AS_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_AS_COV),)
FLAGS_PURIFY_AS_COV=
endif



ifeq ($(FLAGS_PURIFY_LD_EXE),)
FLAGS_PURIFY_LD_EXE=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_OPT),)
FLAGS_PURIFY_LD_EXE_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_DBG),)
FLAGS_PURIFY_LD_EXE_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_PROFILE),)
FLAGS_PURIFY_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_COV),)
FLAGS_PURIFY_LD_EXE_COV=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS),)
FLAGS_PURIFY_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS_OPT),)
FLAGS_PURIFY_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS_DBG),)
FLAGS_PURIFY_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_PURIFY_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS_COV),)
FLAGS_PURIFY_LD_EXE_LOADLIBS_COV=
endif


ifeq ($(FLAGS_PURIFY_LD_SHLIB),)
FLAGS_PURIFY_LD_SHLIB=-fPIC -G -dy
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_OPT),)
FLAGS_PURIFY_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_DBG),)
FLAGS_PURIFY_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_PROFILE),)
FLAGS_PURIFY_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_LOADLIBS),)
FLAGS_PURIFY_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_PURIFY_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_PURIFY_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_PURIFY_LD_SHLIB_LOADLIBS_PROFILE=
endif


ifeq ($(FLAGS_PURIFY_LD_INCOBJ),)
FLAGS_PURIFY_LD_INCOBJ=-Wl,-r
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_OPT),)
FLAGS_PURIFY_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_DBG),)
FLAGS_PURIFY_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_PROFILE),)
FLAGS_PURIFY_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_COV),)
FLAGS_PURIFY_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_PURIFY_AR_LIB),)
FLAGS_PURIFY_AR_LIB=rc
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_OPT),)
FLAGS_PURIFY_AR_LIB_OPT=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_DBG),)
FLAGS_PURIFY_AR_LIB_DBG=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_PROFILE),)
FLAGS_PURIFY_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_COV),)
FLAGS_PURIFY_AR_LIB_COV=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS),)
FLAGS_PURIFY_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS_OPT),)
FLAGS_PURIFY_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS_DBG),)
FLAGS_PURIFY_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_PURIFY_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS_COV),)
FLAGS_PURIFY_AR_LIB_LOADLIBS_COV=
endif


# DOn't strip purify builds
ifeq ($(FLAGS_PURIFY_STRIP_EXE),)
FLAGS_PURIFY_STRIP_EXE=
endif
ifeq ($(FLAGS_PURIFY_STRIP_SHLIB),)
FLAGS_PURIFY_STRIP_SHLIB=
endif
ifeq ($(FLAGS_PURIFY_STRIP_LIB),)
FLAGS_PURIFY_STRIP_LIB=
endif



#
# Cross compiler tool chain for Cavium MIPS64 linux 
#
# Only cross compiling tool chains provide these. These
# allow end point make files to construct platform strings
# approiate to the cross compiler's target platform.
# Really, these have to be specified, since we do not
# have a programatic way of determining what the target
# platform is. (and in the generally cross compiling problem,
# you could be compiling for N platforms on the build host.)
XC_CAVIUMMIPS64_SDK_REVMAJOR=1
XC_CAVIUMMIPS64_SDK_REVMINOR=0
XC_CAVIUMMIPS64_SDK_REVPATCH=0
XC_CAVIUMMIPS64_SDK_HOME=/usr/local/Cavium_Networks-$(XC_CAVIUMMIPS64_SDK_REVMAJOR).$(XC_CAVIUMMIPS64_SDK_REVMINOR).$(XC_CAVIUMMIPS64_SDK_REVPATCH)/CN3XXX-SDK

XC_CAVIUMMIPS64_LINUX_TOOLCHAIN_REVMAJOR=$(XC_CAVIUMMIPS64_SDK_REVMAJOR)
XC_CAVIUMMIPS64_LINUX_TOOLCHAIN_REVMINOR=$(XC_CAVIUMMIPS64_SDK_REVMINOR)
XC_CAVIUMMIPS64_LINUX_TOOLCHAIN_REVPATCH=$(XC_CAVIUMMIPS64_SDK_REVPATCH)

XC_CAVIUMMIPS64_LINUX_OS_NAME=Linux
XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR=2
XC_CAVIUMMIPS64_LINUX_OS_REVMINOR=6
XC_CAVIUMMIPS64_LINUX_OS_REVPATCH=10-Cavium-Octeon
XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME=glibc
XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR=2
XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR=3
XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH=3
XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE=mips64
XC_CAVIUMMIPS64_LINUX_OS_MACHINEPROC=octeon
XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET=mips64

XC_CAVIUMMIPS64_LINUX_PLATFORM_FULL=$(call BS_FUNC_GEN_PLATFORM_FULL,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_FALLBACK_1=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_1,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_FALLBACK_2=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_2,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_FALLBACK_3=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_3,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_FALLBACK_4=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_4,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_FALLBACK_5=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_5,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_FALLBACK_6=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_6,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_FALLBACK_7=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_7,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))

XC_CAVIUMMIPS64_LINUX_PLATFORM_LEGACYFALLBACK_1=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_1,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_LEGACYFALLBACK_2=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_2,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_LEGACYFALLBACK_3=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_3,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_LINUX_PLATFORM_LEGACYFALLBACK_4=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_4,\
	$(XC_CAVIUMMIPS64_LINUX_OS_NAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_LINUX_OS_RUNTIMEREVPATCH))



ifeq ($(BIN_XC_CAVIUMMIPS64_LINUX_CC),)
BIN_XC_CAVIUMMIPS64_LINUX_CC=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mips64-octeon-linux-gnu-gcc
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_LINUX_CXX),)
BIN_XC_CAVIUMMIPS64_LINUX_CXX=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mips64-octeon-linux-gnu-g++ \
    -I$(XC_CAVIUMMIPS64_SDK_HOME)/tools/lib/gcc/mips64-octeon-linux/3.4.3/include \
    -I$(XC_CAVIUMMIPS64_SDK_HOME)/tools/lib/gcc/mips64-octeon-linux/3.4.3/install-tools/include \
    -I$(XC_CAVIUMMIPS64_SDK_HOME)/tools/include/c++/3.4.3/mipsisa64-octeon-elf

endif
ifeq ($(BIN_XC_CAVIUMMIPS64_LINUX_AS),)
BIN_XC_CAVIUMMIPS64_LINUX_AS=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mips64-octeon-linux-gnu-gcc
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_LINUX_CPP),)
BIN_XC_CAVIUMMIPS64_LINUX_CPP=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mips64-octeon-linux-gnu-gcc -E
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_LINUX_LD),)
BIN_XC_CAVIUMMIPS64_LINUX_LD=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mips64-octeon-linux-gnu-gcc
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_LINUX_AR),)
BIN_XC_CAVIUMMIPS64_LINUX_AR=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mips64-octeon-linux-gnu-ar
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_LINUX_STRIP),)
BIN_XC_CAVIUMMIPS64_LINUX_STRIP=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mips64-octeon-linux-gnu-strip
endif


ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CC),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CC=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused \
	-march=octeon \
	-mabi=n32

#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CC_DEP),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CC_DEP=-MM -w
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CC_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CC_DBG=-g3 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CC_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CC_OPT=-O3 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CC_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CC_PROFILE=-pg  
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CC_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CC_COV=-fprofile-arcs -ftest-coverage 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CC_NOASSERT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CC_NOASSERT=-DNDEBUG 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CC_REENT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CC_REENT=-D_REENTRANT 
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CXX),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Wunused \
  -march=octeon \
  -mabi=n32
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_DEP),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_DEP=-MM -w
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_DBG=-g3 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_OPT=-O3  
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_PROFILE=-pg 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_COV=-fprofile-arcs -ftest-coverage 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_NOASSERT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_NOASSERT=-DNDEBUG 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_REENT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_CXX_REENT=-D_REENTRANT 
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AS),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AS= 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AS_DEP),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AS_DEP=-MM -w
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AS_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AS_DBG=-g3 -Wa,--gstabs 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AS_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AS_OPT=-O3  
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AS_PROFILE= 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AS_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AS_COV= 
endif


ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE= -mabi=n32
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_OPT= 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_DBG= 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_PROFILE=-pg -ldl 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_COV= 
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS= 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS_OPT= 
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_EXE_LOADLIBS_LOADLIBS_COV=
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB=-shared -mabi=n32
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_COV=
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ=-Wl,-r
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB=rc
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_COV=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS_OPT),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS_DBG),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS_COV),)
FLAGS_XC_CAVIUMMIPS64_LINUX_AR_LIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_STRIP_EXE),)
FLAGS_XC_CAVIUMMIPS64_LINUX_STRIP_EXE= --strip-unneeded
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_STRIP_SHLIB),)
FLAGS_XC_CAVIUMMIPS64_LINUX_STRIP_SHLIB= --discard-all
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_LINUX_STRIP_LIB),)
FLAGS_XC_CAVIUMMIPS64_LINUX_STRIP_LIB= --discard-all
endif



#
# Cross compiler tool chain for Raza MIPS64 linux 
#
# Only cross compiling tool chains provide these. These
# allow end point make files to construct platform strings
# approiate to the cross compiler's target platform.
# Really, these have to be specified, since we do not
# have a programatic way of determining what the target
# platform is. (and in the generally cross compiling problem,
# you could be compiling for N platforms on the build host.)
XC_RAZAMIPS64_LINUX_OS_NAME=Linux
XC_RAZAMIPS64_LINUX_OS_REVMAJOR=2
XC_RAZAMIPS64_LINUX_OS_REVMINOR=6
XC_RAZAMIPS64_LINUX_OS_REVPATCH=10-Raza-XLR
XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME=glibc
XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR=2
XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR=3
XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH=2
XC_RAZAMIPS64_LINUX_OS_MACHINETYPE=mips64
XC_RAZAMIPS64_LINUX_OS_MACHINEPROC=xlr
XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET=mips64

XC_RAZAMIPS64_LINUX_PLATFORM_FULL=$(call BS_FUNC_GEN_PLATFORM_FULL,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_FALLBACK_1=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_1,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_FALLBACK_2=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_2,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_FALLBACK_3=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_3,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_FALLBACK_4=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_4,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_FALLBACK_5=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_5,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_FALLBACK_6=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_6,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_FALLBACK_7=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_7,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))

XC_RAZAMIPS64_LINUX_PLATFORM_LEGACYFALLBACK_1=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_1,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_LEGACYFALLBACK_2=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_2,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_LEGACYFALLBACK_3=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_3,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))
XC_RAZAMIPS64_LINUX_PLATFORM_LEGACYFALLBACK_4=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_4,\
	$(XC_RAZAMIPS64_LINUX_OS_NAME),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_REVPATCH),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINEINSTSET),\
	$(XC_RAZAMIPS64_LINUX_OS_MACHINETYPE),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMENAME),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMAJOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVMINOR),\
	$(XC_RAZAMIPS64_LINUX_OS_RUNTIMEREVPATCH))



ifeq ($(BIN_XC_RAZAMIPS64_LINUX_CC),)
BIN_XC_RAZAMIPS64_LINUX_CC=/usr/local/rmi_06282005/mipscross/crosstool/gcc-3.4.3-glibc-2.3.5/mipsisa32-xlr-linux/bin/mipsisa32-xlr-linux-gcc
endif
ifeq ($(BIN_XC_RAZAMIPS64_LINUX_CXX),)
BIN_XC_RAZAMIPS64_LINUX_CXX=/usr/local/rmi_06282005/mipscross/crosstool/gcc-3.4.3-glibc-2.3.5/mipsisa32-xlr-linux/bin/mipsisa32-xlr-linux-g++
#    -I$(XC_CAVIUMMIPS64_SDK_HOME)/tools/lib/gcc/mips64-octeon-linux/3.4.3/include \
#    -I$(XC_CAVIUMMIPS64_SDK_HOME)/tools/lib/gcc/mips64-octeon-linux/3.4.3/install-tools/include \
#    -I$(XC_CAVIUMMIPS64_SDK_HOME)/tools/include/c++/3.4.3/mipsisa64-octeon-elf
endif
ifeq ($(BIN_XC_RAZAMIPS64_LINUX_AS),)
BIN_XC_RAZAMIPS64_LINUX_AS=/usr/local/rmi_06282005/mipscross/crosstool/gcc-3.4.3-glibc-2.3.5/mipsisa32-xlr-linux/bin/mipsisa32-xlr-linux-gcc
endif
ifeq ($(BIN_XC_RAZAMIPS64_LINUX_CPP),)
BIN_XC_RAZAMIPS64_LINUX_CPP=/usr/local/rmi_06282005/mipscross/crosstool/gcc-3.4.3-glibc-2.3.5/mipsisa32-xlr-linux/bin/mipsisa32-xlr-linux-cpp
endif
ifeq ($(BIN_XC_RAZAMIPS64_LINUX_LD),)
BIN_XC_RAZAMIPS64_LINUX_LD=/usr/local/rmi_06282005/mipscross/crosstool/gcc-3.4.3-glibc-2.3.5/mipsisa32-xlr-linux/bin/mipsisa32-xlr-linux-gcc
endif
ifeq ($(BIN_XC_RAZAMIPS64_LINUX_AR),)
BIN_XC_RAZAMIPS64_LINUX_AR=/usr/local/rmi_06282005/mipscross/crosstool/gcc-3.4.3-glibc-2.3.5/mipsisa32-xlr-linux/bin/mipsisa32-xlr-linux-ar
endif
ifeq ($(BIN_XC_RAZAMIPS64_LINUX_STRIP),)
BIN_XC_RAZAMIPS64_LINUX_STRIP=/usr/local/rmi_06282005/mipscross/crosstool/gcc-3.4.3-glibc-2.3.5/mipsisa32-xlr-linux/bin/mipsisa32-xlr-linux-strip
endif


ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CC),)
FLAGS_XC_RAZAMIPS64_LINUX_CC=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused 
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CC_DEP),)
FLAGS_XC_RAZAMIPS64_LINUX_CC_DEP=-MM -w
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CC_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_CC_DBG=-g3
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CC_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_CC_OPT=-O3
#-march=xlr
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CC_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_CC_PROFILE=-pg
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CC_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CC_NOASSERT),)
FLAGS_XC_RAZAMIPS64_LINUX_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CC_REENT),)
FLAGS_XC_RAZAMIPS64_LINUX_CC_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CXX),)
FLAGS_XC_RAZAMIPS64_LINUX_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CXX_DEP),)
FLAGS_XC_RAZAMIPS64_LINUX_CXX_DEP=-MM -w
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CXX_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_CXX_DBG=-g3
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CXX_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_CXX_OPT=-O3
#-march=octeon
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CXX_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CXX_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CXX_NOASSERT),)
FLAGS_XC_RAZAMIPS64_LINUX_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_CXX_REENT),)
FLAGS_XC_RAZAMIPS64_LINUX_CXX_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AS),)
FLAGS_XC_RAZAMIPS64_LINUX_AS=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AS_DEP),)
FLAGS_XC_RAZAMIPS64_LINUX_AS_DEP=-MM -w
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AS_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_AS_DBG=-g3 -Wa,--gstabs
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AS_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_AS_OPT=-O3
#-march=octeon
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AS_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_AS_PROFILE=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AS_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_AS_COV=
endif


ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_OPT=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_DBG=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_COV=
endif

ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_EXE_LOADLIBS_LOADLIBS_COV=
endif

ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB=-shared
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_COV=
endif

ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ=-Wl,-r
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB=rc
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_OPT=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_DBG=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_COV=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS_OPT),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS_DBG),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS_COV),)
FLAGS_XC_RAZAMIPS64_LINUX_AR_LIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_STRIP_EXE),)
FLAGS_XC_RAZAMIPS64_LINUX_STRIP_EXE= --strip-unneeded
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_STRIP_SHLIB),)
FLAGS_XC_RAZAMIPS64_LINUX_STRIP_SHLIB= --discard-all
endif
ifeq ($(FLAGS_XC_RAZAMIPS64_LINUX_STRIP_LIB),)
FLAGS_XC_RAZAMIPS64_LINUX_STRIP_LIB= --discard-all
endif



#
# Cross compiler tool chain for Cavium MIPS64 simple executive
#
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_TOOLCHAIN_REVMAJOR=$(XC_CAVIUMMIPS64_SDK_REVMAJOR)
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_TOOLCHAIN_REVMINOR=$(XC_CAVIUMMIPS64_SDK_REVMINOR)
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_TOOLCHAIN_REVPATCH=$(XC_CAVIUMMIPS64_SDK_REVPATCH)
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME=CaviumSimpleExecutive
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR=$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_TOOLCHAIN_REVMAJOR)
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR=$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_TOOLCHAIN_REVMINOR)
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH=$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_TOOLCHAIN_REVPATCH)
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME=CaviumSimpleExecutive
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR=$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_TOOLCHAIN_REVMAJOR)
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR=$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_TOOLCHAIN_REVMINOR)
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH=$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_TOOLCHAIN_REVPATCH)
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE=mips64
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEPROC=octeon
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET=mips64

XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_FULL=$(call BS_FUNC_GEN_PLATFORM_FULL,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_FALLBACK_1=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_1,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_FALLBACK_2=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_2,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_FALLBACK_3=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_3,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_FALLBACK_4=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_4,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_FALLBACK_5=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_5,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_FALLBACK_6=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_6,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_FALLBACK_7=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_7,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))

XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_LEGACYFALLBACK_1=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_1,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_LEGACYFALLBACK_2=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_2,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_LEGACYFALLBACK_3=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_3,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))
XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_PLATFORM_LEGACYFALLBACK_4=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_4,\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_NAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_REVPATCH),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINEINSTSET),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_MACHINETYPE),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMENAME),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMAJOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVMINOR),\
	$(XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_OS_RUNTIMEREVPATCH))



ifeq ($(BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC),)
BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mipsisa64-octeon-elf-gcc
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX),)
BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mipsisa64-octeon-elf-g++ \
    -I$(XC_CAVIUMMIPS64_SDK_HOME)/tools/lib/gcc/mipsisa64-octeon-elf/3.4.3/include \
    -I$(XC_CAVIUMMIPS64_SDK_HOME)/tools/lib/gcc/mipsisa64-octeon-elf/3.4.3/install-tools/include \
    -I$(XC_CAVIUMMIPS64_SDK_HOME)/tools/mipsisa64-octeon-elf/include
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS),)
BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mipsisa64-octeon-elf-gcc
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CPP),)
BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CPP=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mipsisa64-octeon-elf-gcc -E
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD),)
BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mipsisa64-octeon-elf-gcc
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR),)
BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mipsisa64-octeon-elf-ar
endif
ifeq ($(BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_STRIP),)
BIN_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_STRIP=$(XC_CAVIUMMIPS64_SDK_HOME)/tools/bin/mipsisa64-octeon-elf-strip
endif


ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_DEP),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_DEP=-MM -w
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_DBG=-g3
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_OPT=-O3  -march=octeon
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_PROFILE=-pg
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_NOASSERT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_REENT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CC_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_DEP),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_DEP=-MM -w
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_DBG=-g3
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_OPT=-O3  -march=octeon
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_NOASSERT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_REENT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_CXX_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_DEP),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_DEP=-MM -w
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_DBG=-g3 -Wa,--gstabs
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_OPT=-O3  -march=octeon
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AS_COV=
endif


ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_COV=
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_EXE_LOADLIBS_LOADLIBS_COV=
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB=-shared
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_COV=
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ=-Wl,-r
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB=rc
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_COV=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS_OPT),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS_DBG),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS_COV),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_AR_LIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_STRIP_EXE),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_STRIP_EXE= --strip-unneeded
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_STRIP_SHLIB),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_STRIP_SHLIB= --discard-all
endif
ifeq ($(FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_STRIP_LIB),)
FLAGS_XC_CAVIUMMIPS64_SIMPLEEXECUTIVE_STRIP_LIB= --discard-all
endif





#
# Tool chain neutral 
#

ifeq ($(FLAGS_CC),)
FLAGS_CC=-D_GNU_SOURCE
endif
ifeq ($(FLAGS_CC_DBG),)
FLAGS_CC_DBG=
endif
ifeq ($(FLAGS_CC_OPT),)
FLAGS_CC_OPT=
endif
ifeq ($(FLAGS_CC_PROFILE),)
FLAGS_CC_PROFILE=
endif
ifeq ($(FLAGS_CC_COV),)
FLAGS_CC_COV=
endif
ifeq ($(FLAGS_CC_NOASSERT),)
FLAGS_CC_NOASSERT=
endif
ifeq ($(FLAGS_CC_REENT),)
FLAGS_CC_REENT=
endif


ifeq ($(FLAGS_CXX),)
FLAGS_CXX=-D_GNU_SOURCE
endif
ifeq ($(FLAGS_CXX_DBG),)
FLAGS_CXX_DBG=
endif
ifeq ($(FLAGS_CXX_OPT),)
FLAGS_CXX_OPT=
endif
ifeq ($(FLAGS_CXX_PROFILE),)
FLAGS_CXX_PROFILE=
endif
ifeq ($(FLAGS_CXX_COV),)
FLAGS_CXX_COV=
endif
ifeq ($(FLAGS_CXX_NOASSERT),)
FLAGS_CXX_NOASSERT=
endif
ifeq ($(FLAGS_CXX_REENT),)
FLAGS_CXX_REENT=
endif


ifeq ($(FLAGS_AS),)
FLAGS_AS=
endif
ifeq ($(FLAGS_AS_DBG),)
FLAGS_AS_DBG=
endif
ifeq ($(FLAGS_AS_OPT),)
FLAGS_AS_OPT=
endif
ifeq ($(FLAGS_AS_PROFILE),)
FLAGS_AS_PROFILE=
endif
ifeq ($(FLAGS_AS_COV),)
FLAGS_AS_COV=
endif


ifeq ($(FLAGS_LD_EXE),)
FLAGS_LD_EXE=
endif
ifeq ($(FLAGS_LD_EXE_OPT),)
FLAGS_LD_EXE_OPT=
endif
ifeq ($(FLAGS_LD_EXE_DBG),)
FLAGS_LD_EXE_DBG=
endif
ifeq ($(FLAGS_LD_EXE_PROFILE),)
FLAGS_LD_EXE_PROFILE=
endif
ifeq ($(FLAGS_LD_EXE_COV),)
FLAGS_LD_EXE_COV=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS),)
FLAGS_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS_OPT),)
FLAGS_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS_DBG),)
FLAGS_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS_COV),)
FLAGS_LD_EXE_LOADLIBS_COV=
endif


ifeq ($(FLAGS_LD_SHLIB),)
FLAGS_LD_SHLIB=
endif
ifeq ($(FLAGS_LD_SHLIB_OPT),)
FLAGS_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_LD_SHLIB_DBG),)
FLAGS_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_LD_SHLIB_PROFILE),)
FLAGS_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_LD_SHLIB_COV),)
FLAGS_LD_SHLIB_COV=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS),)
FLAGS_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS_COV),)
FLAGS_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_LD_INCOBJ),)
FLAGS_LD_INCOBJ=
endif
ifeq ($(FLAGS_LD_INCOBJ_OPT),)
FLAGS_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_LD_INCOBJ_DBG),)
FLAGS_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_LD_INCOBJ_PROFILE),)
FLAGS_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_LD_INCOBJ_COV),)
FLAGS_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS),)
FLAGS_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_LD_INCOBJ_LOADLIBS_COV=
endif


ifeq ($(FLAGS_AR_LIB),)
FLAGS_AR_LIB=
endif
ifeq ($(FLAGS_AR_LIB_OPT),)
FLAGS_AR_LIB_OPT=
endif
ifeq ($(FLAGS_AR_LIB_DBG),)
FLAGS_AR_LIB_DBG=
endif
ifeq ($(FLAGS_AR_LIB_PROFILE),)
FLAGS_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_AR_LIB_COV),)
FLAGS_AR_LIB_COV=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS),)
FLAGS_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS_OPT),)
FLAGS_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS_DBG),)
FLAGS_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS_COV),)
FLAGS_AR_LIB_LOADLIBS_COV=
endif



ifeq ($(FLAGS_VENDOR_STRIP_EXE),)
FLAGS_STRIP_EXE=
endif
ifeq ($(FLAGS_VENDOR_STRIP_SHLIB),)
FLAGS_STRIP_SHLIB=
endif
ifeq ($(FLAGS_VENDOR_STRIP_LIB),)
FLAGS_STRIP_LIB=
endif

