#
# Tool chain neutral 
#


#
# Gnu tool chain
#
ifeq ($(BIN_GNU_CC),)
BIN_GNU_CC=/usr/bin/gcc
endif
ifeq ($(BIN_GNU_CXX),)
BIN_GNU_CXX=/usr/bin/g++
endif
ifeq ($(BIN_GNU_AS),)
BIN_GNU_AS=/usr/bin/gcc
endif
ifeq ($(BIN_GNU_CPP),)
BIN_GNU_CPP=/usr/bin/gcc -E
endif
ifeq ($(BIN_GNU_LD),)
BIN_GNU_LD=/usr/bin/gcc
endif
ifeq ($(BIN_GNU_AR),)
BIN_GNU_AR=/usr/bin/ar
endif
ifeq ($(BIN_GNU_STRIP),)
BIN_GNU_STRIP=/usr/bin/strip
endif


ifeq ($(FLAGS_GNU_CC),)
FLAGS_GNU_CC=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_GNU_CC_DEP),)
FLAGS_GNU_CC_DEP=-MM
endif
ifeq ($(FLAGS_GNU_CC_DBG),)
FLAGS_GNU_CC_DBG=-g3
endif
ifeq ($(FLAGS_GNU_CC_OPT),)
FLAGS_GNU_CC_OPT=-O3
endif
ifeq ($(FLAGS_GNU_CC_PROFILE),)
FLAGS_GNU_CC_PROFILE=-pg
endif
ifeq ($(FLAGS_GNU_CC_COV),)
FLAGS_GNU_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_GNU_CC_NOASSERT),)
FLAGS_GNU_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_GNU_CC_REENT),)
FLAGS_GNU_CC_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_GNU_CXX),)
FLAGS_GNU_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Wmissing-prototypes \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_GNU_CXX_DEP),)
FLAGS_GNU_CXX_DEP=-MM
endif
ifeq ($(FLAGS_GNU_CXX_DBG),)
FLAGS_GNU_CXX_DBG=-g3
endif
ifeq ($(FLAGS_GNU_CXX_OPT),)
FLAGS_GNU_CXX_OPT=-O3
endif
ifeq ($(FLAGS_GNU_CXX_PROFILE),)
FLAGS_GNU_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_GNU_CXX_COV),)
FLAGS_GNU_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_GNU_CXX_NOASSERT),)
FLAGS_GNU_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_GNU_CXX_REENT),)
FLAGS_GNU_CXX_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_GNU_AS),)
FLAGS_GNU_AS=
endif
ifeq ($(FLAGS_GNU_AS_DEP),)
FLAGS_GNU_AS_DEP=-MM
endif
ifeq ($(FLAGS_GNU_AS_DBG),)
FLAGS_GNU_AS_DBG=-g3 -Wa,--gstabs
endif
ifeq ($(FLAGS_GNU_AS_OPT),)
FLAGS_GNU_AS_OPT=-O3
endif
ifeq ($(FLAGS_GNU_AS_PROFILE),)
FLAGS_GNU_AS_PROFILE=
endif
ifeq ($(FLAGS_GNU_AS_COV),)
FLAGS_GNU_AS_COV=
endif


ifeq ($(FLAGS_GNU_LD_EXE),)
FLAGS_GNU_LD_EXE=
endif
ifeq ($(FLAGS_GNU_LD_EXE_OPT),)
FLAGS_GNU_LD_EXE_OPT=
endif
ifeq ($(FLAGS_GNU_LD_EXE_DBG),)
FLAGS_GNU_LD_EXE_DBG=
endif
ifeq ($(FLAGS_GNU_LD_EXE_PROFILE),)
FLAGS_GNU_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_GNU_LD_EXE_COV),)
FLAGS_GNU_LD_EXE_COV=
endif

ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS),)
FLAGS_GNU_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS_OPT),)
FLAGS_GNU_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS_DBG),)
FLAGS_GNU_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_GNU_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_EXE_LOADLIBS_COV),)
FLAGS_GNU_LD_EXE_LOADLIBS_PROFILE=
endif

ifeq ($(FLAGS_GNU_LD_SHLIB),)
FLAGS_GNU_LD_SHLIB=-shared
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_OPT),)
FLAGS_GNU_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_DBG),)
FLAGS_GNU_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_PROFILE),)
FLAGS_GNU_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_COV),)
FLAGS_GNU_LD_SHLIB_COV=
endif

ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS),)
FLAGS_GNU_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_GNU_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_GNU_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_GNU_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_SHLIB_LOADLIBS_COV),)
FLAGS_GNU_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_GNU_LD_INCOBJ),)
FLAGS_GNU_LD_INCOBJ=-Wl,-r
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_OPT),)
FLAGS_GNU_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_DBG),)
FLAGS_GNU_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_PROFILE),)
FLAGS_GNU_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_COV),)
FLAGS_GNU_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_GNU_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_GNU_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_GNU_AR_LIB),)
FLAGS_GNU_AR_LIB=rc
endif
ifeq ($(FLAGS_GNU_AR_LIB_OPT),)
FLAGS_GNU_AR_LIB_OPT=
endif
ifeq ($(FLAGS_GNU_AR_LIB_DBG),)
FLAGS_GNU_AR_LIB_DBG=
endif
ifeq ($(FLAGS_GNU_AR_LIB_PROFILE),)
FLAGS_GNU_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_GNU_AR_LIB_COV),)
FLAGS_GNU_AR_LIB_COV=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS),)
FLAGS_GNU_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS_OPT),)
FLAGS_GNU_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS_DBG),)
FLAGS_GNU_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_GNU_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_GNU_AR_LIB_LOADLIBS_COV),)
FLAGS_GNU_AR_LIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_GNU_STRIP_EXE),)
FLAGS_GNU_STRIP_EXE= --strip-unneeded
endif
ifeq ($(FLAGS_GNU_STRIP_SHLIB),)
FLAGS_GNU_STRIP_SHLIB= --discard-all
endif
ifeq ($(FLAGS_GNU_STRIP_LIB),)
FLAGS_GNU_STRIP_LIB= --discard-all
endif





#
# Vendor tool chain
#
ifeq ($(BIN_VENDOR_CC),)
BIN_VENDOR_CC=/usr/bin/gcc
endif
ifeq ($(BIN_VENDOR_CXX),)
BIN_VENDOR_CXX=/usr/bin/g++
endif
ifeq ($(BIN_VENDOR_AS),)
BIN_VENDOR_AS=/usr/bin/gcc
endif
ifeq ($(BIN_VENDOR_CPP),)
BIN_VENDOR_CPP=/usr/bin/gcc -E
endif
ifeq ($(BIN_VENDOR_LD),)
BIN_VENDOR_LD=/usr/bin/ld
endif
ifeq ($(BIN_VENDOR_AR),)
BIN_VENDOR_AR=/usr/bin/ar
endif
ifeq ($(BIN_VENDOR_STRIP),)
BIN_VENDOR_STRIP=/usr/bin/strip
endif



ifeq ($(FLAGS_VENDOR_CC),)
FLAGS_VENDOR_CC=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_VENDOR_CC_DEP),)
FLAGS_VENDOR_CC_DEP=-MM
endif
ifeq ($(FLAGS_VENDOR_CC_DBG),)
FLAGS_VENDOR_CC_DBG=-g
endif
ifeq ($(FLAGS_VENDOR_CC_OPT),)
FLAGS_VENDOR_CC_OPT=-O
endif
ifeq ($(FLAGS_VENDOR_CC_PROFILE),)
FLAGS_VENDOR_CC_PROFILE=--pg
endif
ifeq ($(FLAGS_VENDOR_CC_COV),)
FLAGS_VENDOR_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_VENDOR_CC_NOASSERT),)
FLAGS_VENDOR_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_VENDOR_CC_REENT),)
FLAGS_VENDOR_CC_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_VENDOR_CXX),)
FLAGS_VENDOR_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_VENDOR_CXX_DEP),)
FLAGS_VENDOR_CXX_DEP=-MM
endif
ifeq ($(FLAGS_VENDOR_CXX_DBG),)
FLAGS_VENDOR_CXX_DBG=-g
endif
ifeq ($(FLAGS_VENDOR_CXX_OPT),)
FLAGS_VENDOR_CXX_OPT=-O
endif
ifeq ($(FLAGS_VENDOR_CXX_PROFILE),)
FLAGS_VENDOR_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_VENDOR_CXX_COV),)
FLAGS_VENDOR_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_VENDOR_CXX_NOASSERT),)
FLAGS_VENDOR_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_VENDOR_CXX_REENT),)
FLAGS_VENDOR_CXX_REENT=-D_REENTRANT
endif


ifeq ($(FLAGS_VENDOR_AS),)
FLAGS_VENDOR_AS=
endif
ifeq ($(FLAGS_VENDOR_AS_DEP),)
FLAGS_VENDOR_AS_DEP=-MM
endif
ifeq ($(FLAGS_VENDOR_AS_DBG),)
FLAGS_VENDOR_AS_DBG=-g3 -Wa,--gstabs
endif
ifeq ($(FLAGS_VENDOR_AS_OPT),)
FLAGS_VENDOR_AS_OPT=-O3
endif
ifeq ($(FLAGS_VENDOR_AS_PROFILE),)
FLAGS_VENDOR_AS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_AS_COV),)
FLAGS_VENDOR_AS_COV=
endif


ifeq ($(FLAGS_VENDOR_LD_EXE),)
FLAGS_VENDOR_LD_EXE=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_OPT),)
FLAGS_VENDOR_LD_EXE_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_DBG),)
FLAGS_VENDOR_LD_EXE_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_PROFILE),)
FLAGS_VENDOR_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_COV),)
FLAGS_VENDOR_LD_EXE_COV=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS),)
FLAGS_VENDOR_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS_OPT),)
FLAGS_VENDOR_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS_DBG),)
FLAGS_VENDOR_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_VENDOR_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_LD_EXE_LOADLIBS_COV),)
FLAGS_VENDOR_LD_EXE_LOADLIBS_COV=
endif


ifeq ($(FLAGS_VENDOR_LD_SHLIB),)
FLAGS_VENDOR_LD_SHLIB=-shared
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_OPT),)
FLAGS_VENDOR_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_DBG),)
FLAGS_VENDOR_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_PROFILE),)
FLAGS_VENDOR_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_COV),)
FLAGS_VENDOR_LD_SHLIB_COV=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_LD_SHLIB_LOADLIBS_COV),)
FLAGS_VENDOR_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_VENDOR_LD_INCOBJ),)
FLAGS_VENDOR_LD_INCOBJ=-r
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_OPT),)
FLAGS_VENDOR_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_DBG),)
FLAGS_VENDOR_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_PROFILE),)
FLAGS_VENDOR_LD_INCOBJ_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_COV),)
FLAGS_VENDOR_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_VENDOR_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_VENDOR_AR_LIB),)
FLAGS_VENDOR_AR_LIB=rc
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_OPT),)
FLAGS_VENDOR_AR_LIB_OPT=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_DBG),)
FLAGS_VENDOR_AR_LIB_DBG=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_PROFILE),)
FLAGS_VENDOR_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_COV),)
FLAGS_VENDOR_AR_LIB_COV=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS),)
FLAGS_VENDOR_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS_OPT),)
FLAGS_VENDOR_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS_DBG),)
FLAGS_VENDOR_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_VENDOR_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDOR_AR_LIB_LOADLIBS_COV),)
FLAGS_VENDOR_AR_LIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_VENDOR_STRIP_EXE),)
FLAGS_VENDOR_STRIP_EXE= --strip-unneeded
endif
ifeq ($(FLAGS_VENDOR_STRIP_SHLIB),)
FLAGS_VENDOR_STRIP_SHLIB= --discard-all
endif
ifeq ($(FLAGS_VENDOR_STRIP_LIB),)
FLAGS_VENDOR_STRIP_LIB= --discard-all
endif

#
# Purify & Gnu tool chain
#
ifeq ($(BIN_PURIFY_CC),)
BIN_PURIFY_CC=$(BIN_FALSE)
endif
ifeq ($(BIN_PURIFY_CXX),)
BIN_PURIFY_CXX=$(BIN_FALSE)
endif
ifeq ($(BIN_PURIFY_AS),)
BIN_PURIFY_AS=$(BIN_FALSE)
endif
ifeq ($(BIN_PURIFY_CPP),)
BIN_PURIFY_CPP=$(BIN_FALSE)
endif
ifeq ($(BIN_PURIFY_LD),)
BIN_PURIFY_LD=$(BIN_FALSE)
endif
ifeq ($(BIN_PURIFY_AR),)
BIN_PURIFY_AR=$(BIN_FALSE)
endif
# Don't strip purify builds
ifeq ($(BIN_PURIFY_STRIP),)
BIN_PURIFY_STRIP=$(BIN_TRUE)
endif




ifeq ($(FLAGS_PURIFY_CC),)
FLAGS_PURIFY_CC=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_PURIFY_CC_DEP),)
FLAGS_PURIFY_CC_DEP=-MM
endif
ifeq ($(FLAGS_PURIFY_CC_DBG),)
FLAGS_PURIFY_CC_DBG=-g3
endif
ifeq ($(FLAGS_PURIFY_CC_OPT),)
FLAGS_PURIFY_CC_OPT=-O3
endif
ifeq ($(FLAGS_PURIFY_CC_PROFILE),)
FLAGS_PURIFY_CC_PROFILE=-pg
endif
ifeq ($(FLAGS_PURIFY_CC_COV),)
FLAGS_PURIFY_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_PURIFY_CC_NOASSERT),)
FLAGS_PURIFY_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_PURIFY_CC_REENT),)
FLAGS_PURIFY_CC_REENT=-D_REENTRANT
endif


ifeq ($(FLAGS_PURIFY_CXX),)
FLAGS_PURIFY_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_PURIFY_CXX_DEP),)
FLAGS_PURIFY_CXX_DEP=-MM
endif
ifeq ($(FLAGS_PURIFY_CXX_DBG),)
FLAGS_PURIFY_CXX_DBG=-g3
endif
ifeq ($(FLAGS_PURIFY_CXX_OPT),)
FLAGS_PURIFY_CXX_OPT=-O3
endif
ifeq ($(FLAGS_PURIFY_CXX_PROFILE),)
FLAGS_PURIFY_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_PURIFY_CXX_COV),)
FLAGS_PURIFY_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_PURIFY_CXX_NOASSERT),)
FLAGS_PURIFY_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_PURIFY_CXX_REENT),)
FLAGS_PURIFY_CXX_REENT=-D_REENTRANT
endif


ifeq ($(FLAGS_PURIFY_AS),)
FLAGS_PURIFY_AS=
endif
ifeq ($(FLAGS_PURIFY_AS_DEP),)
FLAGS_PURIFY_AS_DEP=-MM
endif
ifeq ($(FLAGS_PURIFY_AS_DBG),)
FLAGS_PURIFY_AS_DBG=-g3
endif
ifeq ($(FLAGS_PURIFY_AS_OPT),)
FLAGS_PURIFY_AS_OPT=-O3
endif
ifeq ($(FLAGS_PURIFY_AS_PROFILE),)
FLAGS_PURIFY_AS_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_AS_COV),)
FLAGS_PURIFY_AS_COV=
endif



ifeq ($(FLAGS_PURIFY_LD_EXE),)
FLAGS_PURIFY_LD_EXE=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_OPT),)
FLAGS_PURIFY_LD_EXE_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_DBG),)
FLAGS_PURIFY_LD_EXE_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_PROFILE),)
FLAGS_PURIFY_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_COV),)
FLAGS_PURIFY_LD_EXE_COV=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS),)
FLAGS_PURIFY_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS_OPT),)
FLAGS_PURIFY_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS_DBG),)
FLAGS_PURIFY_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_PURIFY_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_LD_EXE_LOADLIBS_COV),)
FLAGS_PURIFY_LD_EXE_LOADLIBS_COV=
endif


ifeq ($(FLAGS_PURIFY_LD_SHLIB),)
FLAGS_PURIFY_LD_SHLIB=-fPIC -G -dy
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_OPT),)
FLAGS_PURIFY_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_DBG),)
FLAGS_PURIFY_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_PROFILE),)
FLAGS_PURIFY_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_LOADLIBS),)
FLAGS_PURIFY_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_PURIFY_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_PURIFY_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_PURIFY_LD_SHLIB_LOADLIBS_PROFILE=
endif


ifeq ($(FLAGS_PURIFY_LD_INCOBJ),)
FLAGS_PURIFY_LD_INCOBJ=-Wl,-r
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_OPT),)
FLAGS_PURIFY_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_DBG),)
FLAGS_PURIFY_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_PROFILE),)
FLAGS_PURIFY_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_COV),)
FLAGS_PURIFY_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_PURIFY_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_PURIFY_AR_LIB),)
FLAGS_PURIFY_AR_LIB=rc
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_OPT),)
FLAGS_PURIFY_AR_LIB_OPT=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_DBG),)
FLAGS_PURIFY_AR_LIB_DBG=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_PROFILE),)
FLAGS_PURIFY_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_COV),)
FLAGS_PURIFY_AR_LIB_COV=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS),)
FLAGS_PURIFY_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS_OPT),)
FLAGS_PURIFY_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS_DBG),)
FLAGS_PURIFY_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_PURIFY_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_PURIFY_AR_LIB_LOADLIBS_COV),)
FLAGS_PURIFY_AR_LIB_LOADLIBS_COV=
endif


# DOn't strip purify builds
ifeq ($(FLAGS_PURIFY_STRIP_EXE),)
FLAGS_PURIFY_STRIP_EXE=
endif
ifeq ($(FLAGS_PURIFY_STRIP_SHLIB),)
FLAGS_PURIFY_STRIP_SHLIB=
endif
ifeq ($(FLAGS_PURIFY_STRIP_LIB),)
FLAGS_PURIFY_STRIP_LIB=
endif





#
# tool chain neutral
#

ifeq ($(FLAGS_CC),)
FLAGS_CC=-D_GNU_SOURCE
endif
ifeq ($(FLAGS_CC_DBG),)
FLAGS_CC_DBG=
endif
ifeq ($(FLAGS_CC_OPT),)
FLAGS_CC_OPT=
endif
ifeq ($(FLAGS_CC_PROFILE),)
FLAGS_CC_PROFILE=
endif
ifeq ($(FLAGS_CC_COV),)
FLAGS_CC_COV=
endif
ifeq ($(FLAGS_CC_NOASSERT),)
FLAGS_CC_NOASSERT=
endif
ifeq ($(FLAGS_CC_REENT),)
FLAGS_CC_REENT=
endif


ifeq ($(FLAGS_CXX),)
FLAGS_CXX=-D_GNU_SOURCE
endif
ifeq ($(FLAGS_CXX_DBG),)
FLAGS_CXX_DBG=
endif
ifeq ($(FLAGS_CXX_OPT),)
FLAGS_CXX_OPT=
endif
ifeq ($(FLAGS_CXX_PROFILE),)
FLAGS_CXX_PROFILE=
endif
ifeq ($(FLAGS_CXX_COV),)
FLAGS_CXX_COV=
endif
ifeq ($(FLAGS_CXX_NOASSERT),)
FLAGS_CXX_NOASSERT=
endif
ifeq ($(FLAGS_CXX_REENT),)
FLAGS_CXX_REENT=
endif


ifeq ($(FLAGS_AS),)
FLAGS_AS=
endif
ifeq ($(FLAGS_AS_DBG),)
FLAGS_AS_DBG=
endif
ifeq ($(FLAGS_AS_OPT),)
FLAGS_AS_OPT=
endif
ifeq ($(FLAGS_AS_PROFILE),)
FLAGS_AS_PROFILE=
endif
ifeq ($(FLAGS_AS_COV),)
FLAGS_AS_COV=
endif


ifeq ($(FLAGS_LD_EXE),)
FLAGS_LD_EXE=
endif
ifeq ($(FLAGS_LD_EXE_OPT),)
FLAGS_LD_EXE_OPT=
endif
ifeq ($(FLAGS_LD_EXE_DBG),)
FLAGS_LD_EXE_DBG=
endif
ifeq ($(FLAGS_LD_EXE_PROFILE),)
FLAGS_LD_EXE_PROFILE=
endif
ifeq ($(FLAGS_LD_EXE_COV),)
FLAGS_LD_EXE_COV=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS),)
FLAGS_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS_OPT),)
FLAGS_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS_DBG),)
FLAGS_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_LD_EXE_LOADLIBS_COV),)
FLAGS_LD_EXE_LOADLIBS_COV=
endif


ifeq ($(FLAGS_LD_SHLIB),)
FLAGS_LD_SHLIB=
endif
ifeq ($(FLAGS_LD_SHLIB_OPT),)
FLAGS_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_LD_SHLIB_DBG),)
FLAGS_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_LD_SHLIB_PROFILE),)
FLAGS_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_LD_SHLIB_COV),)
FLAGS_LD_SHLIB_COV=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS),)
FLAGS_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_LD_SHLIB_LOADLIBS_COV),)
FLAGS_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_LD_INCOBJ),)
FLAGS_LD_INCOBJ=
endif
ifeq ($(FLAGS_LD_INCOBJ_OPT),)
FLAGS_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_LD_INCOBJ_DBG),)
FLAGS_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_LD_INCOBJ_PROFILE),)
FLAGS_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_LD_INCOBJ_COV),)
FLAGS_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS),)
FLAGS_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_LD_INCOBJ_LOADLIBS_COV=
endif


ifeq ($(FLAGS_AR_LIB),)
FLAGS_AR_LIB=
endif
ifeq ($(FLAGS_AR_LIB_OPT),)
FLAGS_AR_LIB_OPT=
endif
ifeq ($(FLAGS_AR_LIB_DBG),)
FLAGS_AR_LIB_DBG=
endif
ifeq ($(FLAGS_AR_LIB_PROFILE),)
FLAGS_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_AR_LIB_COV),)
FLAGS_AR_LIB_COV=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS),)
FLAGS_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS_OPT),)
FLAGS_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS_DBG),)
FLAGS_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_AR_LIB_LOADLIBS_COV),)
FLAGS_AR_LIB_LOADLIBS_COV=
endif



ifeq ($(FLAGS_VENDOR_STRIP_EXE),)
FLAGS_STRIP_EXE=
endif
ifeq ($(FLAGS_VENDOR_STRIP_SHLIB),)
FLAGS_STRIP_SHLIB=
endif
ifeq ($(FLAGS_VENDOR_STRIP_LIB),)
FLAGS_STRIP_LIB=
endif

