ifeq ($(BUILDSTAMP_COMMENT),)
BUILDSTAMP_COMMENT=Copyright (c) $(BS_DATE_YEAR) nCircle. All rights reserved.
endif

# numbers for date provided by the build system core are leading zero padded
# for pretty string printing. We don't want this for integer C constants
# since this means "octal" integer constants.
ifeq ($(BUILDSTAMP_DATE_YEAR),)
BUILDSTAMP_DATE_YEAR=$(BS_DATE_YEAR)
endif

ifeq ($(BUILDSTAMP_DATE_MONTH),)
BUILDSTAMP_DATE_MONTH=$(BS_DATE_MONTH_NOPAD)
endif

ifeq ($(BUILDSTAMP_DATE_DAY),)
BUILDSTAMP_DATE_DAY=$(BS_DATE_DAY_NOPAD)
endif

ifeq ($(BUILDSTAMP_DATE_HOUR),)
BUILDSTAMP_DATE_HOUR=$(BS_DATE_HOUR_NOPAD)
endif

ifeq ($(BUILDSTAMP_DATE_MINUTE),)
BUILDSTAMP_DATE_MINUTE=$(BS_DATE_MINUTE_NOPAD)
endif

ifeq ($(BUILDSTAMP_DATE_SECOND),)
BUILDSTAMP_DATE_SECOND=$(BS_DATE_SECOND_NOPAD)
endif

ifeq ($(BUILDSTAMP_DATE_STRING),)
BUILDSTAMP_DATE_STRING:=$(shell $(BIN_PRINTF) "%d/%d/%d %02d:%02d:%02d" $(BUILDSTAMP_DATE_YEAR) $(BUILDSTAMP_DATE_MONTH) $(BUILDSTAMP_DATE_DAY) $(BUILDSTAMP_DATE_HOUR) $(BUILDSTAMP_DATE_MINUTE) $(BUILDSTAMP_DATE_SECOND))
endif



ifeq ($(BUILDSTAMP_USERNAME),)
BUILDSTAMP_USERNAME:=$(BS_USERNAME)
endif

ifeq ($(BUILDSTAMP_HOSTNAME),)
BUILDSTAMP_HOSTNAME=$(BS_OS_HOSTNAME)
endif



ifeq ($(BUILDSTAMP_OS_NAME),)
BUILDSTAMP_OS_NAME=$(BS_OS_NAME)
endif

ifeq ($(BUILDSTAMP_OS_REVMAJOR),)
BUILDSTAMP_OS_REVMAJOR=$(BS_OS_REVMAJOR)
endif

ifeq ($(BUILDSTAMP_OS_REVMINOR),)
BUILDSTAMP_OS_REVMINOR=$(BS_OS_REVMINOR)
endif

ifeq ($(BUILDSTAMP_OS_REVPATCH),)
BUILDSTAMP_OS_REVPATCH=$(BS_OS_REVPATCH)
endif



ifeq ($(BUILDSTAMP_OS_RUNTIMENAME),)
BUILDSTAMP_OS_RUNTIMENAME=$(BS_OS_RUNTIMENAME)
endif

ifeq ($(BUILDSTAMP_OS_RUNTIMEREVMAJOR),)
BUILDSTAMP_OS_RUNTIMEREVMAJOR=$(BS_OS_RUNTIMEREVMAJOR)
endif

ifeq ($(BUILDSTAMP_OS_RUNTIMEREVMINOR),)
BUILDSTAMP_OS_RUNTIMEREVMINOR=$(BS_OS_RUNTIMEREVMINOR)
endif

ifeq ($(BUILDSTAMP_OS_RUNTIMEREVPATCH),)
BUILDSTAMP_OS_RUNTIMEREVPATCH=$(BS_OS_RUNTIMEREVPATCH)
endif



ifeq ($(BUILDSTAMP_MACHINETYPE),)
BUILDSTAMP_MACHINETYPE=$(BS_OS_MACHINETYPE)
endif

ifeq ($(BUILDSTAMP_MACHINEPROC),)
BUILDSTAMP_MACHINEPROC=$(BS_OS_MACHINEPROC)
endif

ifeq ($(BUILDSTAMP_MACHINEINSTSET),)
BUILDSTAMP_MACHINEINSTSET=$(BS_OS_MACHINEINSTSET)
endif




ifeq ($(BUILDSTAMP_NAME),)
BUILDSTAMP_NAME=NoName
endif

ifeq ($(BUILDSTAMP_REVISION_MAJOR),)
BUILDSTAMP_REVISION_MAJOR=1
endif

ifeq ($(BUILDSTAMP_REVISION_MINOR),)
BUILDSTAMP_REVISION_MINOR=0
endif

ifeq ($(BUILDSTAMP_REVISION_PATCH),)
BUILDSTAMP_REVISION_PATCH=0
endif

ifeq ($(BUILDSTAMP_REVISION_BUILD),)
BUILDSTAMP_REVISION_BUILD=0
endif

ifeq ($(BUILDSTAMP_REVISION_SRCVER),)
BUILDSTAMP_REVISION_SRCVER=0
endif


ifeq ($(BUILDSTAMP_REVISION_STRING),)
BUILDSTAMP_REVISION_STRING=$(BUILDSTAMP_REVISION_MAJOR)$(if $(strip $(BUILDSTAMP_REVISION_MINOR)),.$(strip $(BUILDSTAMP_REVISION_MINOR)))$(if $(strip $(BUILDSTAMP_REVISION_PATCH)),.$(strip $(BUILDSTAMP_REVISION_PATCH)))$(if $(strip $(BUILDSTAMP_REVISION_BUILD)),-$(strip $(BUILDSTAMP_REVISION_BUILD)))
endif

