COMPONENT_ROOT=..
BS_ROOT=$(COMPONENT_ROOT)/build3
include $(BS_ROOT)/defines.mk


SUBDIR_TARGETS= \
	cc-obj \
	cxx-obj \
	exe-1

#	autoconf \ # this would generally be one of your first sub dirs.
#	buildstamp \ # this would generally be one of your first sub dirs.



include $(BS_ROOT)/rules.mk
