ifeq ($(COMPONENT_DISTROOT),)
COMPONENT_DISTROOT=/home/dist
endif

ifeq ($(COMPONENT_IMPORT_TARGET_ROOT),)
COMPONENT_IMPORT_TARGET_ROOT=$(COMPONENT_ROOT)/components$(if $(strip $(BS_VTAG)),-$(strip $(BS_VTAG)))
endif


#ifeq ($(COMPONENT_DEFAULT_PLATFORM_LIST),)
#COMPONENT_DEFAULT_PLATFORM_LIST=$(BS_PLATFORM_ARCH_FULL) \
#$(BS_PLATFORM_ARCH_FALLBACK_1) \
#$(BS_PLATFORM_ARCH_FALLBACK_2) \
#$(BS_PLATFORM_ARCH_FALLBACK_5) \
#$(BS_PLATFORM_ARCH_FALLBACK_6) \
#$(BS_PLATFORM_ARCH_FALLBACK_7) \
#$(BS_PLATFORM_ARCH_LEGACYFALLBACK_1) \
#$(BS_PLATFORM_ARCH_LEGACYFALLBACK_2) \
#$(BS_PLATFORM_ARCH_LEGACYFALLBACK_3) \
#$(BS_PLATFORM_ARCH_LEGACYFALLBACK_4)
#endif

ifeq ($(COMPONENT_DEFAULT_PLATFORM_LIST),)
COMPONENT_DEFAULT_PLATFORM_LIST=$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_FULL,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_FALLBACK_1,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_FALLBACK_2,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_FALLBACK_3,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_FALLBACK_5,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_FALLBACK_6,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_FALLBACK_7,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_LEGACYFALLBACK_1,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_LEGACYFALLBACK_2,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_LEGACYFALLBACK_3,$(NC_CONTROL_TOOLCHAIN)) \
$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_LEGACYFALLBACK_4,$(NC_CONTROL_TOOLCHAIN)) \


# This is actually too generic for is now. 
#$(call NC_FUNC_GET_TOOLCHAIN_PLATFORM_FALLBACK_4,$(NC_CONTROL_TOOLCHAIN)) \
#$(BS_PLATFORM_NOARCH)

endif


ifeq ($(COMPONENT_DIST_COMPATIBILITY_PLATFORMS),)
COMPONENT_DIST_COMPATIBILITY_PLATFORMS=$(COMPONENT_DEFAULT_PLATFORM_LIST)
endif

ifeq ($(COMPONENT_DIST_COMPATIBILITY_PLATFORMS_AND_VTAG),)
COMPONENT_DIST_COMPATIBILITY_PLATFORMS_AND_VTAG=$(addsuffix $(if $(strip $(BS_VTAG)),-$(strip $(BS_VTAG))),$(COMPONENT_DIST_COMPATIBILITY_PLATFORMS))
endif
