

#
# Cross compiler tool chain for Alteon MIPS64 sunos 
#
# Only cross compiling tool chains provide these. These
# allow end point make files to construct platform strings
# approiate to the cross compiler's target platform.
# Really, these have to be specified, since we do not
# have a programatic way of determining what the target
# platform is. (and in the generally cross compiling problem,
# you could be compiling for N platforms on the build host.)
XC_ALTEONMIPS64_SUN_OS_NAME=SunOS
XC_ALTEONMIPS64_SUN_OS_REVMAJOR=5
XC_ALTEONMIPS64_SUN_OS_REVMINOR=8
XC_ALTEONMIPS64_SUN_OS_REVPATCH=-Nortel-Alteon
XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME=sb1sim
XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR=2
XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR=1
XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH=1
XC_ALTEONMIPS64_SUN_OS_MACHINETYPE=mips64
XC_ALTEONMIPS64_SUN_OS_MACHINEPROC=alteon
XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET=mips64

XC_ALTEONMIPS64_SUN_PLATFORM_FULL=$(call BS_FUNC_GEN_PLATFORM_FULL,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_1=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_1,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_2=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_2,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_3=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_3,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_4=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_4,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_5=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_5,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_6=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_6,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_7=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_7,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_6=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_8,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_9=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_9,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_10=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_10,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_11=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_11,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))
XC_ALTEONMIPS64_SUN_PLATFORM_FALLBACK_12=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_12,\
	$(XC_ALTEONMIPS64_SUN_OS_NAME),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_REVPATCH),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINEINSTSET),\
	$(XC_ALTEONMIPS64_SUN_OS_MACHINETYPE),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMENAME),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMAJOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVMINOR),\
	$(XC_ALTEONMIPS64_SUN_OS_RUNTIMEREVPATCH))



ifeq ($(BIN_XC_ALTEONMIPS64_SUN_CC),)
BIN_XC_ALTEONMIPS64_SUN_CC=/usr/local/sbtools/sparc-solaris-5.6/mips64-sb1sim-2.1.1/bin/mips64-sb1sim-gcc
endif
ifeq ($(BIN_XC_ALTEONMIPS64_SUN_CXX),)
BIN_XC_ALTEONMIPS64_SUN_CXX=/usr/local/sbtools/sparc-solaris-5.6/mips64-sb1sim-2.1.1/bin/mips64-sb1sim-g++
endif
ifeq ($(BIN_XC_ALTEONMIPS64_SUN_AS),)
BIN_XC_ALTEONMIPS64_SUN_AS=/usr/local/sbtools/sparc-solaris-5.6/mips64-sb1sim-2.1.1/bin/mips64-sb1sim-gcc
endif
ifeq ($(BIN_XC_ALTEONMIPS64_SUN_CPP),)
BIN_XC_ALTEONMIPS64_SUN_CPP=/usr/local/sbtools/sparc-solaris-5.6/mips64-sb1sim-2.1.1/bin/mips64-sb1sim-gcc -E
endif
ifeq ($(BIN_XC_ALTEONMIPS64_SUN_LD),)
BIN_XC_ALTEONMIPS64_SUN_LD=/usr/local/sbtools/sparc-solaris-5.6/mips64-sb1sim-2.1.1/bin/mips64-sb1sim-gcc
endif
ifeq ($(BIN_XC_ALTEONMIPS64_SUN_AR),)
BIN_XC_ALTEONMIPS64_SUN_AR=/usr/local/sbtools/sparc-solaris-5.6/mips64-sb1sim-2.1.1/bin/mips64-sb1sim-ar
endif
ifeq ($(BIN_XC_ALTEONMIPS64_SUN_STRIP),)
BIN_XC_ALTEONMIPS64_SUN_STRIP=/usr/local/sbtools/sparc-solaris-5.6/mips64-sb1sim-2.1.1/bin/mips64-sb1sim-strip
endif


ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CC),)
FLAGS_XC_ALTEONMIPS64_SUN_CC=-DBIG_ENDIAN -DXP_NO_XP_INTTYPES_H -DXP_DEFINE_INTTYPES -DXP_NO_64BIT_INT_SUPPORT -DXP_DEFINE_INT_CONSTANTS -W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wunused \
	-I/usr/local/sbtools/sparc-solaris-5.6/mips64-sb1sim-2.1.1/mips64-sb1sim/sys-include \
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CC_DEP),)
FLAGS_XC_ALTEONMIPS64_SUN_CC_DEP=-MM
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CC_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_CC_DBG=-g3
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CC_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_CC_OPT=-O3
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CC_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_CC_PROFILE=-pg
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CC_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CC_NOASSERT),)
FLAGS_XC_ALTEONMIPS64_SUN_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CC_REENT),)
FLAGS_XC_ALTEONMIPS64_SUN_CC_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CXX),)
FLAGS_XC_ALTEONMIPS64_SUN_CXX=-DBIG_ENDIAN -DXP_NO_XP_INTTYPES_H -DXP_DEFINE_INTTYPES -DXP_NO_64BIT_INT_SUPPORT -DXP_DEFINE_INT_CONSTANTS -W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Wunused \
	-I/usr/local/sbtools/sparc-solaris-5.6/mips64-sb1sim-2.1.1/mips64-sb1sim/sys-include \
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CXX_DEP),)
FLAGS_XC_ALTEONMIPS64_SUN_CXX_DEP=-MM
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CXX_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_CXX_DBG=-g3
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CXX_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_CXX_OPT=-O3
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CXX_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CXX_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CXX_NOASSERT),)
FLAGS_XC_ALTEONMIPS64_SUN_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_CXX_REENT),)
FLAGS_XC_ALTEONMIPS64_SUN_CXX_REENT=-D_REENTRANT
endif

ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AS),)
FLAGS_XC_ALTEONMIPS64_SUN_AS=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AS_DEP),)
FLAGS_XC_ALTEONMIPS64_SUN_AS_DEP=-MM
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AS_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_AS_DBG=-g3 -Wa,--gstabs
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AS_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_AS_OPT=-O3
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AS_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_AS_PROFILE=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AS_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_AS_COV=
endif


ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_OPT=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_DBG=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_COV=
endif

ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_EXE_LOADLIBS_LOADLIBS_COV=
endif

ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB=-shared
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_COV=
endif

ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ=-Wl,-r
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_PROFILE=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB=rc
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_OPT=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_DBG=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_COV=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS_OPT),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS_DBG),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS_COV),)
FLAGS_XC_ALTEONMIPS64_SUN_AR_LIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_STRIP_EXE),)
FLAGS_XC_ALTEONMIPS64_SUN_STRIP_EXE=--strip-unneeded
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_STRIP_SHLIB),)
FLAGS_XC_ALTEONMIPS64_SUN_STRIP_SHLIB=--discard-all
endif
ifeq ($(FLAGS_XC_ALTEONMIPS64_SUN_STRIP_LIB),)
FLAGS_XC_ALTEONMIPS64_SUN_STRIP_LIB=--discard-all
endif

