# macros to provide backwards compatibility with older versions of build3
# The build system is moving towards better supporing cross compilation,
# so a seperation of the target architecure from the build host architechure 
# is now needed. 
BS_OS_HOSTNAME=$(BS_BUILDHOST_HOSTNAME)
BS_OS_NAME=$(BS_BUILDHOST_OS_NAME)
BS_OS_REVMAJOR=$(BS_BUILDHOST_OS_REVMAJOR)
BS_OS_REVMINOR=$(BS_BUILDHOST_OS_REVMINOR)
BS_OS_REVPATCH=$(BS_BUILDHOST_OS_REVPATCH)
BS_OS_RUNTIMEOLDNAME=$(BS_BUILDHOST_OS_RUNTIMEOLDNAME)
BS_OS_RUNTIMENAME=$(BS_BUILDHOST_OS_RUNTIMENAME)
BS_OS_RUNTIMEREVMAJOR=$(BS_BUILDHOST_OS_RUNTIMEREVMAJOR)
BS_OS_RUNTIMEREVMINOR=$(BS_BUILDHOST_OS_RUNTIMEREVMINOR)
BS_OS_RUNTIMEREVPATCH=$(BS_BUILDHOST_OS_RUNTIMEREVPATCH)
BS_OS_MACHINETYPE=$(BS_BUILDHOST_OS_MACHINETYPE)
BS_OS_MACHINEPROC=$(BS_BUILDHOST_OS_MACHINEPROC)
BS_OS_MACHINEINSTSET=$(BS_BUILDHOST_OS_MACHINEINSTSET)


