ifeq ($(XML_VALIDATE_CLASS),)
XML_VALIDATE_CLASS=Validate
endif

ifeq ($(XML_VALIDATE_CP),)
XML_VALIDATE_CP=$(call COMPONENT_FUNC_IMPORT_COMPUTE_TARGETDIR,bb-md-validate)/tools/validate:$(call COMPONENT_FUNC_IMPORT_COMPUTE_TARGETDIR,bb-md-validate)/tools/validate/xercesImpl.jar
endif

ifeq ($(XML_VALIDATE_JAVAFLAGS),)
XML_VALIDATE_JAVAFLAGS=-client
endif

ifeq ($(XML_VALIDATE_CMD),)
XML_VALIDATE_CMD=$(BIN_JAVA) $(XML_VALIDATE_JAVAFLAGS) -cp $(XML_VALIDATE_CP) $(XML_VALIDATE_CLASS)
endif

ifeq ($(XML_TRANSFORM_CLASS),)
XML_TRANSFORM_CLASS=Transform
endif

ifeq ($(XML_TRANSFORM_CP),)
XML_TRANSFORM_CP=$(call COMPONENT_FUNC_IMPORT_COMPUTE_TARGETDIR,bb-md-validate)/tools/transform
endif

ifeq ($(XML_TRANSFORM_JAVAFLAGS),)
XML_TRANSFORM_JAVAFLAGS=-client -DentityExpansionLimit=1000000
endif

ifeq ($(XML_TRANSFORM_CMD),)
XML_TRANSFORM_CMD=$(BIN_JAVA) $(XML_TRANSFORM_JAVAFLAGS) -cp $(XML_TRANSFORM_CP) $(XML_TRANSFORM_CLASS)
endif

ifeq ($(XML_TRANSFORM_XSL),)
XML_TRANSFORM_XSL=
endif

ifeq ($(XML_TFSPLITXSL),)
XML_TFSPLITXSL=
endif

ifeq ($(XML_TFSPLITCMD),)
XML_TFSPLITCMD=
endif

ifeq ($(XML_TFSPLITBXSL),)
XML_TFSPLITBXSL=
endif
