#
# Vendor C++ only tool chain
#
ifeq ($(BIN_VENDORCXX_CC),)
BIN_VENDORCXX_CC=/usr/bin/g++
BIN_VENDORCXX_CC_OUTPUTFLAG=-o 
endif
ifeq ($(BIN_VENDORCXX_CXX),)
BIN_VENDORCXX_CXX=/usr/bin/g++
BIN_VENDORCXX_CXX_OUTPUTFLAG=-o 
endif
ifeq ($(BIN_VENDORCXX_AS),)
BIN_VENDORCXX_AS=/usr/bin/g++
BIN_VENDORCXX_AS_OUTPUTFLAG=-o 
endif
ifeq ($(BIN_VENDORCXX_CPP),)
BIN_VENDORCXX_CPP=/usr/bin/g++ -E
BIN_VENDORCXX_CPP_OUTPUTFLAG=-o 
endif
ifeq ($(BIN_VENDORCXX_LD),)
#BIN_VENDORCXX_LD=/usr/bin/ld
BIN_VENDORCXX_LD=/usr/bin/g++
BIN_VENDORCXX_LD_OUTPUTFLAG_EXE=-o 
BIN_VENDORCXX_LD_OUTPUTFLAG_SHLIB=-o 
BIN_VENDORCXX_LD_OUTPUTFLAG_INCOBJ=-o 
endif
ifeq ($(BIN_VENDORCXX_AR),)
BIN_VENDORCXX_AR=/usr/bin/ar
BIN_VENDORCXX_AR_OUTPUTFLAG=
endif
ifeq ($(BIN_VENDORCXX_STRIP),)
BIN_VENDORCXX_STRIP=/usr/bin/strip
endif



ifeq ($(EXTENSION_VENDORCXX_OBJ),)
EXTENSION_VENDORCXX_OBJ=.o
endif
ifeq ($(EXTENSION_VENDORCXX_EXE),)
EXTENSION_VENDORCXX_EXE=
endif
ifeq ($(EXTENSION_VENDORCXX_LIB),)
EXTENSION_VENDORCXX_LIB=.a
endif
ifeq ($(EXTENSION_VENDORCXX_SHLIB),)
EXTENSION_VENDORCXX_SHLIB=.so
endif



ifeq ($(FLAGS_VENDORCXX_CC),)
FLAGS_VENDORCXX_CC= \
	-pipe \
	-Wall \
	-Wformat-security
#	-Wmissing-declarations \
#    -Werror \
#   -W \
#	-Wcast-qual \
#	-Wcast-align \
#	-Wpointer-arith \
#	-Wsign-compare \
#	-Winline \
#	-Waggregate-return \
#	-Wmissing-prototypes \
#	-Wmissing-declarations \
#	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_VENDORCXX_CC_DEP),)
FLAGS_VENDORCXX_CC_DEP=-MM -w
endif
ifeq ($(FLAGS_VENDORCXX_CC_DBG),)
FLAGS_VENDORCXX_CC_DBG=-ggdb -g3
#FLAGS_VENDORCXX_CC_DBG=-gdwarf-2 -g3
endif
ifeq ($(FLAGS_VENDORCXX_CC_OPT),)
FLAGS_VENDORCXX_CC_OPT=-O
endif
ifeq ($(FLAGS_VENDORCXX_CC_PROFILE),)
FLAGS_VENDORCXX_CC_PROFILE=--pg
endif
ifeq ($(FLAGS_VENDORCXX_CC_COV),)
FLAGS_VENDORCXX_CC_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_VENDORCXX_CC_NOASSERT),)
FLAGS_VENDORCXX_CC_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_VENDORCXX_CC_REENT),)
FLAGS_VENDORCXX_CC_REENT=-D_REENTRANT -DWITH_THREADS -D_THREAD_SAFE
endif
ifeq ($(FLAGS_VENDORCXX_CC_PIC),)
FLAGS_VENDORCXX_CC_PIC=-fpic -fPIC
endif

ifeq ($(FLAGS_VENDORCXX_CXX),)
FLAGS_VENDORCXX_CXX=-W \
	-Wall \
	-Wcast-qual \
	-Wcast-align \
	-Wpointer-arith \
	-Wsign-compare \
	-Winline \
	-Waggregate-return \
	-Wmissing-prototypes \
	-Wunused
#	-v \
#	-ftime-report \
#	-fmem-report

endif
ifeq ($(FLAGS_VENDORCXX_CXX_DEP),)
FLAGS_VENDORCXX_CXX_DEP=-MM -w
endif
ifeq ($(FLAGS_VENDORCXX_CXX_DBG),)
FLAGS_VENDORCXX_CXX_DBG=-ggdb -g3
#FLAGS_VENDORCXX_CXX_DBG=-gdwarf-2 -g3
endif
ifeq ($(FLAGS_VENDORCXX_CXX_OPT),)
FLAGS_VENDORCXX_CXX_OPT=-O
endif
ifeq ($(FLAGS_VENDORCXX_CXX_PROFILE),)
FLAGS_VENDORCXX_CXX_PROFILE=-pg
endif
ifeq ($(FLAGS_VENDORCXX_CXX_COV),)
FLAGS_VENDORCXX_CXX_COV=-fprofile-arcs -ftest-coverage
endif
ifeq ($(FLAGS_VENDORCXX_CXX_NOASSERT),)
FLAGS_VENDORCXX_CXX_NOASSERT=-DNDEBUG
endif
ifeq ($(FLAGS_VENDORCXX_CXX_REENT),)
FLAGS_VENDORCXX_CXX_REENT=-D_REENTRANT -DWITH_THREADS -D_THREAD_SAFE
endif
ifeq ($(FLAGS_VENDORCXX_CXX_PIC),)
FLAGS_VENDORCXX_CXX_PIC=-fpic -fPIC
endif


ifeq ($(FLAGS_VENDORCXX_AS),)
FLAGS_VENDORCXX_AS=
endif
ifeq ($(FLAGS_VENDORCXX_AS_DEP),)
FLAGS_VENDORCXX_AS_DEP=-MM -w
endif
ifeq ($(FLAGS_VENDORCXX_AS_DBG),)
FLAGS_VENDORCXX_AS_DBG=-g3 -Wa,--gstabs
endif
ifeq ($(FLAGS_VENDORCXX_AS_OPT),)
FLAGS_VENDORCXX_AS_OPT=-O3
endif
ifeq ($(FLAGS_VENDORCXX_AS_PROFILE),)
FLAGS_VENDORCXX_AS_PROFILE=
endif
ifeq ($(FLAGS_VENDORCXX_AS_COV),)
FLAGS_VENDORCXX_AS_COV=
endif


ifeq ($(FLAGS_VENDORCXX_LD_EXE),)
FLAGS_VENDORCXX_LD_EXE=
endif
ifeq ($(FLAGS_VENDORCXX_LD_EXE_OPT),)
FLAGS_VENDORCXX_LD_EXE_OPT=
endif
ifeq ($(FLAGS_VENDORCXX_LD_EXE_DBG),)
FLAGS_VENDORCXX_LD_EXE_DBG=
endif
ifeq ($(FLAGS_VENDORCXX_LD_EXE_PROFILE),)
FLAGS_VENDORCXX_LD_EXE_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_VENDORCXX_LD_EXE_COV),)
FLAGS_VENDORCXX_LD_EXE_COV=
endif
ifeq ($(FLAGS_VENDORCXX_LD_EXE_LOADLIBS),)
FLAGS_VENDORCXX_LD_EXE_LOADLIBS=
endif
ifeq ($(FLAGS_VENDORCXX_LD_EXE_LOADLIBS_OPT),)
FLAGS_VENDORCXX_LD_EXE_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDORCXX_LD_EXE_LOADLIBS_DBG),)
FLAGS_VENDORCXX_LD_EXE_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDORCXX_LD_EXE_LOADLIBS_PROFILE),)
FLAGS_VENDORCXX_LD_EXE_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDORCXX_LD_EXE_LOADLIBS_COV),)
FLAGS_VENDORCXX_LD_EXE_LOADLIBS_COV=
endif


ifeq ($(FLAGS_VENDORCXX_LD_SHLIB),)
FLAGS_VENDORCXX_LD_SHLIB=-shared -Wl,-x
endif
ifeq ($(FLAGS_VENDORCXX_LD_SHLIB_OPT),)
FLAGS_VENDORCXX_LD_SHLIB_OPT=
endif
ifeq ($(FLAGS_VENDORCXX_LD_SHLIB_DBG),)
FLAGS_VENDORCXX_LD_SHLIB_DBG=
endif
ifeq ($(FLAGS_VENDORCXX_LD_SHLIB_PROFILE),)
FLAGS_VENDORCXX_LD_SHLIB_PROFILE=
endif
ifeq ($(FLAGS_VENDORCXX_LD_SHLIB_COV),)
FLAGS_VENDORCXX_LD_SHLIB_COV=
endif
ifeq ($(FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS),)
FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS=
endif
ifeq ($(FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS_OPT),)
FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS_DBG),)
FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS_PROFILE),)
FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS_COV),)
FLAGS_VENDORCXX_LD_SHLIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ),)
FLAGS_VENDORCXX_LD_INCOBJ=-r
endif
ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ_OPT),)
FLAGS_VENDORCXX_LD_INCOBJ_OPT=
endif
ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ_DBG),)
FLAGS_VENDORCXX_LD_INCOBJ_DBG=
endif
ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ_PROFILE),)
FLAGS_VENDORCXX_LD_INCOBJ_PROFILE=-pg -ldl
endif
ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ_COV),)
FLAGS_VENDORCXX_LD_INCOBJ_COV=
endif
ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS),)
FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS=
endif
ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS_OPT),)
FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS_DBG),)
FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS_PROFILE),)
FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS_COV),)
FLAGS_VENDORCXX_LD_INCOBJ_LOADLIBS_COV=
endif

ifeq ($(FLAGS_VENDORCXX_AR_LIB),)
FLAGS_VENDORCXX_AR_LIB=rc
endif
ifeq ($(FLAGS_VENDORCXX_AR_LIB_OPT),)
FLAGS_VENDORCXX_AR_LIB_OPT=
endif
ifeq ($(FLAGS_VENDORCXX_AR_LIB_DBG),)
FLAGS_VENDORCXX_AR_LIB_DBG=
endif
ifeq ($(FLAGS_VENDORCXX_AR_LIB_PROFILE),)
FLAGS_VENDORCXX_AR_LIB_PROFILE=
endif
ifeq ($(FLAGS_VENDORCXX_AR_LIB_COV),)
FLAGS_VENDORCXX_AR_LIB_COV=
endif
ifeq ($(FLAGS_VENDORCXX_AR_LIB_LOADLIBS),)
FLAGS_VENDORCXX_AR_LIB_LOADLIBS=
endif
ifeq ($(FLAGS_VENDORCXX_AR_LIB_LOADLIBS_OPT),)
FLAGS_VENDORCXX_AR_LIB_LOADLIBS_OPT=
endif
ifeq ($(FLAGS_VENDORCXX_AR_LIB_LOADLIBS_DBG),)
FLAGS_VENDORCXX_AR_LIB_LOADLIBS_DBG=
endif
ifeq ($(FLAGS_VENDORCXX_AR_LIB_LOADLIBS_PROFILE),)
FLAGS_VENDORCXX_AR_LIB_LOADLIBS_PROFILE=
endif
ifeq ($(FLAGS_VENDORCXX_AR_LIB_LOADLIBS_COV),)
FLAGS_VENDORCXX_AR_LIB_LOADLIBS_COV=
endif


ifeq ($(FLAGS_VENDORCXX_STRIP_EXE),)
FLAGS_VENDORCXX_STRIP_EXE= --strip-unneeded
endif
ifeq ($(FLAGS_VENDORCXX_STRIP_SHLIB),)
FLAGS_VENDORCXX_STRIP_SHLIB= --discard-all
endif
ifeq ($(FLAGS_VENDORCXX_STRIP_LIB),)
FLAGS_VENDORCXX_STRIP_LIB= --discard-all
endif

