#
# The version of build3/project mentok itself.
#
BS_REVMAJOR=3
BS_REVMINOR=5
BS_REVPATCH=0

#
# Macros needed for bootstrapping the base of the build system.
#
ifeq ($(BIN_PLATFORMUTIL),)
BIN_PLATFORMUTIL=$(BS_ROOT)/util/plat.pl
endif

ifeq ($(BIN_SHADOWTREE),)
BIN_SHADOWTREE=$(BS_ROOT)/util/shadowtree.pl
endif

BS_OS_HOSTNAME:=$(shell $(BIN_PLATFORMUTIL) -n)
BS_OS_NAME:=$(shell $(BIN_PLATFORMUTIL) -s)
BS_OS_REVMAJOR:=$(shell $(BIN_PLATFORMUTIL) -M)
BS_OS_REVMINOR:=$(shell $(BIN_PLATFORMUTIL) -N)
BS_OS_REVPATCH:=$(shell $(BIN_PLATFORMUTIL) -P)
BS_OS_RUNTIMEOLDNAME:=$(shell $(BIN_PLATFORMUTIL) -R)
BS_OS_RUNTIMENAME:=$(shell $(BIN_PLATFORMUTIL) -w)
BS_OS_RUNTIMEREVMAJOR:=$(shell $(BIN_PLATFORMUTIL) -x)
BS_OS_RUNTIMEREVMINOR:=$(shell $(BIN_PLATFORMUTIL) -y)
BS_OS_RUNTIMEREVPATCH:=$(shell $(BIN_PLATFORMUTIL) -z)
BS_OS_MACHINETYPE:=$(shell $(BIN_PLATFORMUTIL) -m)
BS_OS_MACHINEPROC:=$(shell $(BIN_PLATFORMUTIL) -p)
BS_OS_MACHINEINSTSET:=$(shell $(BIN_PLATFORMUTIL) -i)


#
# Functions to munge the OS/runtime details into platform strings for the sake
# of modules that provide this info in make defines over determining them
# from the build machine environment. Cross compliers need to do this.
#
# args: OS name, OS rev major, OS rev minor, OS rev patch
bs_FUNC_GEN_OS_FULL=$(strip $(1))-$(strip $(2))$(if $(3),.$(strip $(3)))$(if $(4),.$(strip $(4)))

# args: OS name, OS rev major, OS rev minor
bs_FUNC_GEN_OS_FALLBACK_1=$(strip $(1))-$(strip $(2))$(if $(3),.$(strip $(3)))

# args: OS name, OS rev major
bs_FUNC_GEN_OS_FALLBACK_2=$(strip $(1))-$(strip $(2))

# args: OS name
bs_FUNC_GEN_OS_FALLBACK_3=$(strip $(1))


# args: runtime name, runtime rev major, runtime rev minor, runtime rev patch
bs_FUNC_GEN_RUNTIME_FULL=$(strip $(1))$(if $(2),-$(strip $(2)))$(if $(3),.$(strip $(3)))$(if $(4),.$(strip $(4)))

# args: runtime name, runtime rev major, runtime rev minor
bs_FUNC_GEN_RUNTIME_FALLBACK_1=$(strip $(1))$(if $(2),-$(strip $(2)))$(if $(3),.$(strip $(3)))

# args: runtime name, runtime rev major
bs_FUNC_GEN_RUNTIME_FALLBACK_2=$(strip $(1))$(if $(2),-$(strip $(2)))

# args: runtime name
bs_FUNC_GEN_RUNTIME_FALLBACK_3=$(strip $(1))

# args: runtime old name
bs_FUNC_GEN_RUNTIME_FALLBACK_4=$(strip $(1))

# Args for all BS_FUNC_GEN_PLATFORM_* functions:
#  (1)OS name 
#  (2)OS major
#  (3)OS minor
#  (4)OS patch
#  (5)machine instruciton set
#  (6)machine type
#  (7)runtime name
#  (8)runtime major
#  (9)runtime minor
#  (10)runtime patch
BS_FUNC_GEN_PLATFORM_FULL=$(call bs_FUNC_GEN_OS_FULL, $(1), $(2), $(3), $(4))-$(strip $(5))-$(call bs_FUNC_GEN_RUNTIME_FULL, $(7), $(8), $(9), $(10))
BS_FUNC_GEN_PLATFORM_FALLBACK_1=$(call bs_FUNC_GEN_OS_FALLBACK_1, $(1), $(2), $(3))-$(strip $(5))-$(call bs_FUNC_GEN_RUNTIME_FULL, $(7), $(8), $(9), $(10))
BS_FUNC_GEN_PLATFORM_FALLBACK_2=$(call bs_FUNC_GEN_OS_FALLBACK_1, $(1), $(2), $(3))-$(strip $(5))
BS_FUNC_GEN_PLATFORM_FALLBACK_3=$(call bs_FUNC_GEN_OS_FALLBACK_3, $(1))-$(strip $(5))
BS_FUNC_GEN_PLATFORM_FALLBACK_4=$(call bs_FUNC_GEN_OS_FALLBACK_3, $(1))
BS_FUNC_GEN_PLATFORM_FALLBACK_5=$(call bs_FUNC_GEN_OS_FULL, $(1), $(2), $(3), $(4))-$(strip $(5))-$(call bs_FUNC_GEN_RUNTIME_FALLBACK_1, $(7), $(8), $(9))
BS_FUNC_GEN_PLATFORM_FALLBACK_6=$(call bs_FUNC_GEN_OS_FALLBACK_1, $(1), $(2), $(3))-$(strip $(5))-$(call bs_FUNC_GEN_RUNTIME_FULL, $(7), $(8), $(9), $(10))
BS_FUNC_GEN_PLATFORM_FALLBACK_7=$(call bs_FUNC_GEN_OS_FALLBACK_1, $(1), $(2), $(3))-$(strip $(5))-$(call bs_FUNC_GEN_RUNTIME_FALLBACK_1, $(7), $(8), $(9))

BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_1=$(call bs_FUNC_GEN_OS_FULL, $(1), $(2), $(3), $(4))-$(strip $(5))
BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_2=$(call bs_FUNC_GEN_OS_FALLBACK_1, $(1), $(2), $(3))-$(strip $(5))
BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_3=$(call bs_FUNC_GEN_OS_FULL, $(1), $(2), $(3), $(4))-$(strip $(6))
BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_4=$(call bs_FUNC_GEN_OS_FALLBACK_1, $(1), $(2), $(3))-$(strip $(6))


BS_PLATFORM_NOARCH=noarch

BS_PLATFORM_ARCH_FULL=$(call BS_FUNC_GEN_PLATFORM_FULL,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_FALLBACK_1=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_1,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_FALLBACK_2=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_2,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_FALLBACK_3=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_3,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_FALLBACK_4=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_4,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_FALLBACK_5=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_5,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_FALLBACK_6=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_6,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_FALLBACK_7=$(call BS_FUNC_GEN_PLATFORM_FALLBACK_7,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_LEGACYFALLBACK_1=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_1,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_LEGACYFALLBACK_2=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_2,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_LEGACYFALLBACK_3=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_3,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))
BS_PLATFORM_ARCH_LEGACYFALLBACK_4=$(call BS_FUNC_GEN_PLATFORM_LEGACYFALLBACK_4,\
	$(BS_OS_NAME),\
	$(BS_OS_REVMAJOR),\
	$(BS_OS_REVMINOR),\
	$(BS_OS_REVPATCH),\
	$(BS_OS_MACHINEINSTSET),\
	$(BS_OS_MACHINETYPE),\
	$(BS_OS_RUNTIMENAME),\
	$(BS_OS_RUNTIMEREVMAJOR),\
	$(BS_OS_RUNTIMEREVMINOR),\
	$(BS_OS_RUNTIMEREVPATCH))

BS_PLATFORM_ARCH_LIST= \
	$(BS_PLATFORM_ARCH_FULL) \
	$(BS_PLATFORM_ARCH_FALLBACK_1) \
	$(BS_PLATFORM_ARCH_FALLBACK_2) \
	$(BS_PLATFORM_ARCH_FALLBACK_3) \
	$(BS_PLATFORM_ARCH_FALLBACK_5) \
	$(BS_PLATFORM_ARCH_FALLBACK_6) \
	$(BS_PLATFORM_ARCH_FALLBACK_7) \
	$(BS_PLATFORM_ARCH_LEGACYFALLBACK_1) \
	$(BS_PLATFORM_ARCH_LEGACYFALLBACK_2) \
	$(BS_PLATFORM_ARCH_LEGACYFALLBACK_3) \
	$(BS_PLATFORM_ARCH_LEGACYFALLBACK_4)

#
# include platform specific base macros
#
-include $(BS_ROOT)/base/defines-base-$(BS_PLATFORM_ARCH_FALLBACK_4).mk
-include $(BS_ROOT)/base/defines-base-$(BS_PLATFORM_ARCH_FALLBACK_3).mk
-include $(BS_ROOT)/base/defines-base-$(BS_PLATFORM_ARCH_FALLBACK_2).mk
-include $(BS_ROOT)/base/defines-base-$(BS_PLATFORM_ARCH_FALLBACK_1).mk
-include $(BS_ROOT)/base/defines-base-$(BS_PLATFORM_ARCH_FULL).mk

#
# Base module step 2.. some general build environment macros and common utilities
#

#
# Bin Programs & scripts
#
ifeq ($(BIN_COMPONENTUTIL),)
BIN_COMPONENTUTIL=$(BIN_PERL) $(BS_ROOT)/util/component-desc-util.pl
endif

ifeq ($(BIN_STATUS_MSG),)
BIN_STATUS_MSG=$(BIN_PERL) $(BS_ROOT)/util/status-msg.pl
endif

#
# Info / Control macros.
#
BS_INFO_PREFIX="+ "
BS_WARN_PREFIX="\*\* "
BS_ERROR_PREFIX="\*\*\* ERROR "


BS_ROOT_TARGET_DIR=./BUILDTARGETS$(if $(strip $(BS_VTAG)),-$(strip $(BS_VTAG)))

BS_FUNC_GEN_TARGET_DIR=$(BS_ROOT_TARGET_DIR)/$(strip $(1))

BS_ARCH_TARGET_DIR=$(call BS_FUNC_GEN_TARGET_DIR, $(BS_PLATFORM_ARCH_FULL))
BS_NOARCH_TARGET_DIR=$(call BS_FUNC_GEN_TARGET_DIR, $(BS_PLATFORM_NOARCH))


BS_CURRENT_SRCDIR_ABSPATH=$(shell $(BIN_PWD))

ifeq ($(COMPONENT_ROOT_ABSPATH),)
COMPONENT_ROOT_ABSPATH:=$(shell $(BIN_CD) $(COMPONENT_ROOT) && $(BIN_PWD))
endif
export COMPONENT_ROOT_ABSPATH

ifeq ($(BS_DATE_YEAR),)
BS_DATE_YEAR:=$(shell $(BIN_DATE) +%Y)
endif
export BS_DATE_YEAR

ifeq ($(BS_DATE_MONTH),)
BS_DATE_MONTH:=$(shell $(BIN_DATE) +%m)
endif
export BS_DATE_MONTH

ifeq ($(BS_DATE_DAY),)
BS_DATE_DAY:=$(shell $(BIN_DATE) +%d)
endif
export BS_DATE_DAY

ifeq ($(BS_DATE_HOUR),)
BS_DATE_HOUR:=$(shell $(BIN_DATE) +%H)
endif
export BS_DATE_HOUR

ifeq ($(BS_DATE_MINUTE),)
BS_DATE_MINUTE:=$(shell $(BIN_DATE) +%M)
endif
export BS_DATE_MINUTE

ifeq ($(BS_DATE_SECOND),)
BS_DATE_SECOND:=$(shell $(BIN_DATE) +%S)
endif
export BS_DATE_SECOND

ifeq ($(BS_USERNAME),)
BS_USERNAME:=$(shell $(BIN_WHOAMI))
endif
export BS_USERNAME
ifeq ($(BS_VERBOSE),)
BS_VERBOSE=0
endif
export BS_VERBOSE


# The build system verbose macro is used to toggle the verbosity of
# the build system as a whole.
ifeq ($(BS_VERBOSE),3)
BS_CMDPREFIX_VERBOSE0=
BS_CMDPREFIX_VERBOSE1=
BS_CMDPREFIX_VERBOSE2=
BS_CMDPREFIX_VERBOSE3=
BS_FUNC_ECHO_VERBOSE0=echo $1
BS_FUNC_ECHO_VERBOSE1=echo $1
BS_FUNC_ECHO_VERBOSE2=echo $1
BS_FUNC_ECHO_VERBOSE3=echo $1
else
ifeq ($(BS_VERBOSE),2)
BS_CMDPREFIX_VERBOSE0=
BS_CMDPREFIX_VERBOSE1=
BS_CMDPREFIX_VERBOSE2=
BS_CMDPREFIX_VERBOSE3=@
BS_FUNC_ECHO_VERBOSE0=echo $1
BS_FUNC_ECHO_VERBOSE1=echo $1
BS_FUNC_ECHO_VERBOSE2=echo $1
BS_FUNC_ECHO_VERBOSE3=
else
ifeq ($(BS_VERBOSE),1)
BS_CMDPREFIX_VERBOSE0=
BS_CMDPREFIX_VERBOSE1=
BS_CMDPREFIX_VERBOSE2=@
BS_CMDPREFIX_VERBOSE3=@
BS_FUNC_ECHO_VERBOSE0=echo $1
BS_FUNC_ECHO_VERBOSE1=echo $1
BS_FUNC_ECHO_VERBOSE2=
BS_FUNC_ECHO_VERBOSE3=
else
# BS_VERBOSE == 0
BS_CMDPREFIX_VERBOSE0=
BS_CMDPREFIX_VERBOSE1=@
BS_CMDPREFIX_VERBOSE2=@
BS_CMDPREFIX_VERBOSE3=@
BS_FUNC_ECHO_VERBOSE0=echo $1
BS_FUNC_ECHO_VERBOSE1=
BS_FUNC_ECHO_VERBOSE2=
BS_FUNC_ECHO_VERBOSE3=
endif
endif
endif
